mpv: add extraConfig
nix-community/home-manager pull request #1417
Opened 2020-07-30 07:36 UTC by AstroSnail

### Description

There exist mpv configurations which cannot be expressed in
programs.mpv.config. For example, it is impossible to use multiple
'profile' attributes. This commit adds the conventional extraConfig
escape hatch to allow for these kinds of configurations.

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [ ] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/rycee/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/rycee/home-manager/blob/master/doc/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/rycee/home-manager/commits/master) for examples.

- ~~If this PR adds a new module~~

  - [ ] ~~Added myself as module maintainer. See [example](https://github.com/rycee/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).~~

  - [ ] ~~Added myself and the module files to `.github/CODEOWNERS`.~~

2020-09-05 22:08 UTC, teto approved these changes

2020-09-06 02:41 UTC, cole-h requested changes
I think it would be better to instead use `lib.generators.toINI` (see https://github.com/NixOS/rfcs/pull/42 for why `extraConfig` is "bad"). Then, one could write:

```nix
{
  # ...

  programs.mpv = {
    enable = true;

    config = {
      profile = "slow";

      slow = {
        framedrop = "no";
      };
    };
  };

  # ...
}
```

and have `toINI` do all the work.

2020-09-06 16:53 UTC, AstroSnail commented
I like cole-h's suggestion. However, if I read the code correctly, `lib.generators.toINI` does not appear to allow for settings outside of a section (in the example cole-h gave, that would be the `profile` attribute).

We can still do a hybrid solution, separating the "main" config from the profiles. The main config is rendered outside of a section, and then the profiles are rendered using `lib.generators.toINI` and appended to the config. The main advantage of this is it preserves backwards compatibility, with the only visible change being the new allowance of lists to represent duplicate keys.

For example:
```nix
{
  # ...

  programs.mpv = {
    enable = true;

    config = {
      profile = [ "gpu-hq" "slow" ];
    };

    profiles = {
      slow = {
        framedrop = "no";
      };
    };
  };

  # ...
}
```

2020-09-07 05:26 UTC, AstroSnail commented
I have created a new pull request for this strategy at #1478. Discussion of it should continue there.

2020-11-03 01:01 UTC, AstroSnail commented
#1478 was merged, closing this one.

2020-11-03 01:01 UTC, closed without merging