chromium: add support for external extensions
nix-community/home-manager pull request #1648
Opened 2020-12-08 20:44 UTC by SebastienWae

### Description
This allows the installation of external (outside of the Chrome Web Store) extensions, both local and remote, based on the [Alternative extension distribution options](https://developer.chrome.com/docs/extensions/mv2/external_extensions/) documentation.
Backward compatibility  for the list of string ids is maintained but I removed it from the example.

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/doc/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

2020-12-08 22:04 UTC, berbiche commented on modules/programs/chromium.nix
> +          types.attrs); # strings are accepted to maintain backward compatibility
Would it be possible to change this to `types.listOf (types.coercedTo

2020-12-08 23:11 UTC, berbiche requested changes
Thanks for the contribution!

2020-12-09 13:29 UTC, SebastienWae commented
@berbiche thanks for the input, let me know I need to make more changes.

Regarding the `updateUrl` type I'm using `str` instead of  `strMatching` because I could not find a regex to validate a url perfectly and handle all the possible edge cases, if someone has a better idea I'm open to suggestion.

2020-12-09 18:51 UTC, berbiche commented on modules/programs/chromium.nix
> +                  type = either path bool;
Please use `nullOr path` instead and set the default to `null`

2020-12-09 18:51 UTC, berbiche commented on modules/programs/chromium.nix
> +                  type = either str bool;
Same as above

2020-12-23 00:05 UTC, rycee commented
Thanks! Rebased to master in 3627ec4de58d7fbda13c82dfec94eace10198f23.

2020-12-23 00:06 UTC, closed without merging