mercurial: Enable configuration of mercurial extensions
nix-community/home-manager pull request #1730
Opened 2021-01-18 17:54 UTC by HolgerPeters

https://github.com/nix-community/home-manager/issues/1729

Fairly standardized use case so it makes sense to map this configuration
in home.nix. This might also enable to use installation paths of
mercurial extensions that are installed via nix.

### Description

### Checklist

- [ ] Change is backwards compatible.

- [ ] Code formatted with `./format`.

- [ ] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [ ] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/doc/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

2021-01-18 18:08 UTC, kalbasit requested changes
Please add a test.

2021-01-18 18:08 UTC, kalbasit commented on modules/programs/mercurial.nix
> +            purge = "";
Are the values ever not empty strings? Can you add an example?

2021-01-18 19:16 UTC, berbiche commented
Please see my comment here https://github.com/nix-community/home-manager/issues/1727#issuecomment-762426821

2021-01-21 20:08 UTC, HolgerPeters commented
hi, I think this PR can be rejected. Fairly new to nix in general and I didn't realize that `extraConfig` can take structural values as a config so there is not much value in my proposal I think.

2021-01-21 20:08 UTC, closed without merging