qutebrowser: fix config location on darwin
nix-community/home-manager pull request #1925
Opened 2021-04-13 01:41 UTC by fortuneteller2k

### Description

Fix #1897 
### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/doc/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

2021-04-23 03:06 UTC, berbiche requested changes
Thanks for the contribution!

2021-04-23 03:06 UTC, berbiche commented on modules/programs/qutebrowser.nix
> +      ".config/qutebrowser/config.py";
```suggestion
      "${config.xdg.configHome}/qutebrowser/config.py";
```

The `.config` folder is not guaranteed to be the user's `$XDG_CONFIG_HOME` 😃

2021-04-23 03:06 UTC, berbiche commented on tests/modules/programs/qutebrowser/keybindings.nix
> +        ".config/qutebrowser/config.py";
This would need to be updated as per the first comment.

2021-04-23 03:06 UTC, berbiche commented on tests/modules/programs/qutebrowser/settings.nix
> +        ".config/qutebrowser/config.py";
Ditto.

2021-04-23 03:06 UTC, berbiche commented on modules/programs/qutebrowser.nix
> +    ] ++ mapAttrsToList (formatLine "c.") cfg.settings
```suggestion
    home.file."${qutebrowserConfig}".text = concatStringsSep "\n" ([
      (if cfg.loadAutoconfig then
        "config.load_autoconfig()"
      else
        "config.load_autoconfig(False)")
    ] ++ mapAttrsToList (formatLine "c.") cfg.settings
```

The expression can be simplified to be a bit cleaner.

2021-04-23 04:18 UTC, berbiche commented
I should have RTFM. `xdg.configHome` is an absolute path.

I think the best solution is to use the same logic as the one in https://github.com/nix-community/home-manager/pull/1930

2021-04-23 05:51 UTC, fortuneteller2k commented
I have no idea why this test is failing but the settings one passed:

```
qutebrowser-keybindings: FAILED
Expected home-files/.config/qutebrowser/config.py to be same as /nix/store/pnsaylx25nqql4zl19ljy136rcbnv48g-qutebrowser-expected-config.py but were different:

For further reference please introspect /nix/store/lciijsiqca42614frkmislk5d9kbkrbb-nmt-report-qutebrowser-keybindings
qutebrowser-settings: OK
```

2021-04-23 05:56 UTC, fortuneteller2k commented on modules/programs/qutebrowser.nix
> +      mkIf (cfg.settings != { } && pkgs.stdenv.hostPlatform.isDarwin) {
On second thought, might be because of `cfg.settings != { }` but I'm not sure, will test when I'm free again.

2021-04-23 06:33 UTC, fortuneteller2k commented
Ok, now the failing test isn't related to qutebrowser.

2021-04-24 09:43 UTC, fortuneteller2k commented
Closing and reopening to restart CI due to #1943 being merged.

2021-04-27 21:53 UTC, berbiche commented
@fortuneteller2k can you rebase your work on the latest changes?

2021-04-28 02:44 UTC, fortuneteller2k commented
Rebased to latest master.

2021-04-28 18:41 UTC, berbiche approved these changes

2021-04-28 18:41 UTC, merged