fzf: option for tmux usage in shell integration
nix-community/home-manager pull request #1926
Opened 2021-04-13 19:12 UTC by afreakk

### Description

Added options for tmux which will be read by fzf shell integrations.
The env variables are not read by the fzf binary, they only change behaviour of fzf shell integrations.
(Like FZF_CTRL_*_* and FZF_ALT_*_* commands.)

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).
(there arent any test cases for fzf)

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/doc/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

2021-04-21 02:29 UTC, berbiche requested changes
Thanks for the contribution!

2021-04-21 02:29 UTC, berbiche commented on modules/programs/fzf.nix
> +
Could these options be nested under a `tmux` setting?

```suggestion
tmux = {
    enableShellIntegration = mkEnableOption ''
        setting FZF_TMUX to 1 which causes shell integration to use fzf-tmux
      '';
    };

    shellIntegrationOptions = mkOption {
      type = types.listOf types.str;
      default = [ ];
      example = [ "-d 40%" ];
      description = ''
        If <options>programs.fzf.tmux.enableShellIntegration<options> is set to true,
        shell integration will use these options for fzf-tmux.
        See fzf-tmux --help for available options.
      '';
    };
}
```

2021-04-21 02:29 UTC, berbiche commented on modules/programs/fzf.nix
> +        FZF_TMUX_OPTS = cfg.tmuxOptionsInShellIntegration;
```suggestion
        FZF_TMUX = if cfg.tmux.enableShellIntegration then "1" else null;
        FZF_TMUX_OPTS = cfg.tmux.shellIntegrationOptions;
```

2021-04-23 02:53 UTC, berbiche requested changes
This needs some small documentation fixes and it's good 👍

2021-04-23 02:53 UTC, berbiche commented on modules/programs/fzf.nix
> +        sets FZF_TMUX=1 which causes shell integration to use fzf-tmux
This expands to `Whether to enable sets FZF_TMUX=1`.
I recommend the initial `setting <literal>FZF_TMUX=1</literal>`.

2021-04-23 02:53 UTC, berbiche commented on modules/programs/fzf.nix
> +          See fzf-tmux --help for available options.
```suggestion
          See <command>fzf-tmux --help</command> for available options.
```

2021-04-28 20:47 UTC, berbiche commented on modules/programs/fzf.nix
> +        example = [ "-d 40%" ];
```suggestion
        example = literalExample ''[ "-d 40%" ]'';
```
One last thing to fix.

2021-04-30 15:08 UTC, sumnerevans requested changes

2021-04-30 15:08 UTC, sumnerevans commented on modules/programs/fzf.nix
> +          If <options>programs.fzf.tmux.enableShellIntegration<options> is set to true,
The build is failing due to the end tag being incorrect. Also, I think it should be `option` not `options`.

```suggestion
          If <option>programs.fzf.tmux.enableShellIntegration</option> is set to true,
```

2021-05-01 22:10 UTC, merged