tmux: use xdg config path
nix-community/home-manager pull request #1928
Opened 2021-04-14 02:06 UTC by marsam

### Description

[Tmux 3.2](https://github.com/tmux/tmux/raw/3.2/CHANGES) includes support to use `$XDG_CONFIG_HOME/tmux/tmux.conf` as
well as `~/.config/tmux/tmux.conf` for configuration file.

Fixes https://github.com/nix-community/home-manager/issues/1558

### Checklist

- [ ] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all`.

- [x] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/doc/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

2021-04-14 13:31 UTC, peterhoeg commented
How would the tests deal with `$XDG_CONFIG_HOME != $HOME/.config`?

2021-04-14 13:45 UTC, teto approved these changes

2021-04-19 16:52 UTC, sumnerevans requested changes

2021-04-19 16:52 UTC, sumnerevans commented on modules/programs/tmux.nix
> +    xdg.configFile."tmux/tmux.conf".text = ''
I think this whole change should be gated behind a new state version. See https://github.com/nix-community/home-manager/pull/1919/files#diff-f1f119fe42c1c025c898ab5a4b5063f7867d8f3d327111f1b029ef13a29fe1dcR128 for an exaple of how to do this.

2021-04-20 03:31 UTC, peterhoeg commented
> -    home.file.".tmux.conf".text = ''
> +    xdg.configFile."tmux/tmux.conf".text = ''
>
> I think this whole change should be gated behind a new state version. See

I disagree. The state version is used if for whatever reason the user needs to do something (the canonical example being
postgres that stores incompatible database files in a version dependent path).

Here we're just generating a file in a new place - the user doesn't (have to) care.

2021-04-23 03:59 UTC, berbiche approved these changes

2021-04-23 07:25 UTC, merged