Dunst: Fix systemd user service for cannot open display
nix-community/home-manager pull request #2080
Opened 2021-06-05 23:41 UTC by aniketd

The systemd user service results in a failed start with
"Cannot open the X11 display".

- [x] Change is backwards compatible.

- [ ] ~~Code formatted with `./format`.~~

- [ ] ~~Code tested through `nix-shell --pure tests -A run.all`.~~

- ~~[ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).~~

- [ ] ~~Commit messages are formatted like~~

    ```
    {component}: {description}

    {long description}
    ```

2021-06-06 15:46 UTC, berbiche requested changes
I disagree with the changes.

If a user wants to run any X11 applications running as a systemd service they should import the DISPLAY environment variable : `systemctl --user import-environment DISPLAY`.

On NixOS systems, this is done automatically by NixOS' xserver module.

On non-NixOS systems, HM's startx (in the xsession modure) should import the DISPLAY environment variable before starting other services.

Hardcoding the `DISPLAY` environment variable will not work in all situations, for instance when using VNC or anything else where the `DISPLAY` might not be `:0`.

Although this isn't mentioned, the wayland-specific option should have been refused for the same reason.

2021-06-06 17:32 UTC, aniketd commented
> I disagree with the changes.

Thanks @berbiche! TIL.

> Although this isn't mentioned, the wayland-specific option should have been refused for the same reason.

Do you mean that removing the `Environment` key/value from the `systemd` service file altogether is the solution?

https://wiki.archlinux.org/title/Systemd/User#Environment_variables states that

> DISPLAY and XAUTHORITY
> DISPLAY is used by any X application to know which display to use and XAUTHORITY to provide a path to the user's .Xauthority file and thus the cookie needed to access the X server. If you plan on launching X applications from systemd units, these variables need to be set. Systemd provides a script in /etc/X11/xinit/xinitrc.d/50-systemd-user.sh to import those variables into the systemd user session on X launch. [3] So unless you start X in a nonstandard way, user services should be aware of the DISPLAY and XAUTHORITY.

2021-06-06 17:47 UTC, berbiche commented
> Do you mean that removing the `Environment` key/value from the `systemd` service file altogether is the solution?

It's not the solution to the problem as the Environment section only overrides existing variables, it doesn't touch the rest of the inherited environment.

2021-06-14 21:25 UTC, aniketd commented
> It's not the solution to the problem as the Environment section only overrides existing variables, it doesn't touch the rest of the inherited environment.

Forgive me, I didn't understand what you mean. Can you explain what would be the solution?

My thought context: The archlinux-wiki link shared above is being interpreted by me as saying that the `DISPLAY` environment variable would not need to be specified at all in the systemd file because it should be imported into the user session on `X` launch because of a `/etc/X11/xinit/xinitrc.d/50-systemd-user.sh`, and user services should be aware of it, unless you start X in a nonstandard way.

2021-06-15 17:05 UTC, berbiche commented
Hi @aniketd,

The workaround you proposed initially is what should be done before starting the service.

As mentioned, Home Manager's xsession module imports the required variables automatically in the systemd session:
https://github.com/nix-community/home-manager/blob/be0e73a308e9c6f778b7dc710ec6c6fe154b8634/modules/xsession.nix#L78-L86

So assuming you have `xsession.enable = true`, and you are starting your WM in the `startx` script, these variables should automatically be imported.

Desktop environments like Gnome and KDE already handle this logic.

I will be closing this PR since a better long-term solution is available and was suggested.

2021-06-15 17:05 UTC, closed without merging

2021-06-15 18:01 UTC, aniketd commented
I haven't moved my `xsession` management over to home-manager yet, its still under `configuration.nix`. I start `i3` using `startx`. But having the following in my `i3/config` solves it for me for the moment (until I switch)

```
exec --no-startup-id systemctl --user import-environment DISPLAY
exec --no-startup-id systemctl --user restart·dunst
```

Thanks for you help.

2021-06-15 18:06 UTC, aniketd commented
This is my current `home.nix`... :slightly_smiling_face: (pretty bare bones)

```nix
{ config, pkgs, ... }:

{
  # Let Home Manager install and manage itself.
  programs.home-manager.enable = true;

  # Home Manager needs a bit of information about you and the
  # paths it should manage.
  home.username = "aniketd";
  home.homeDirectory = "/home/aniketd";

  # This value determines the Home Manager release that your
  # configuration is compatible with. This helps avoid breakage
  # when a new Home Manager release introduces backwards
  # incompatible changes.
  #
  # You can update Home Manager without changing this value. See
  # the Home Manager release notes for a list of state version
  # changes in each release.
  home.stateVersion = "21.05";

  # Custom configuration

  home.packages = with pkgs; [
  ];

  services = {

    caffeine.enable = true;

    dunst = {
      enable = true;
      settings = { # https://raw.githubusercontent.com/dunst-project/dunst/master/dunstrc
        experimental.per_monitor_dpi = false;
        urgency_low = {
          background = "#66ccff";
          foreground = "#000000";
          timeout = 10;
        };
        urgency_normal = {
          background = "#ff9933";
          foreground = "#000000";
          timeout = 10;
        };

        urgency_critical = {
          background = "#ff0066";
          foreground = "#000000";
          # frame_color = "#ff0000"
          timeout = 0;
        };
        global = {
          monitor = 0;
          follow = "mouse";
          geometry = "300x5-30+20";
          program_bar = true;
          progress_bar_height = 10;
          progress_bar_frame_width = 1;
          progress_bar_min_width = 150;
          progress_bar_max_width = 300;
          indicate_hidden = "yes";
          shrink = "no";
          transparency = 0;
          notification_height = 0;
          separator_height = 2;
          padding = 8;
          horizontal_padding = 8;
          text_icon_padding = 0;
          frame_width = 3;
          frame_color = "#003366";
          separator_color = "frame";
          sort = "yes";
          idle_threshold = 120;
          font = "Monospace 10";
          line_height = 0;
          markup = "full";
          # %a appname # %s summary # %b body # %i iconname (with path) # %I iconname (without path) # %p progress value if set ([  0%] to [100%]) or nothing # %n progress value if set without any extra characters # %% Literal %
          # Markup is allowed
          format = "%a\\n<b>%s</b>\\n%b\\n%n\\n";
          alignment = "left";
          vertical_alignment = "center";
          show_age_threshold = 60;
          word_wrap = "yes";
          ellipsize = "middle";
          ignore_newline = "no";
          stack_duplicates = true;
          hide_duplicate_count = false;
          show_indicators = "yes";
          icon_position = "left";
          min_icon_size = 0;
          max_icon_size = 32;
          sticky_history = "yes";
          history_length = 20;
          dmenu = "/run/current-system/sw/bin/dmenu -p dunst:";
          browser = "/run/current-system/sw/bin/firefox -new-tab";
          always_run_script = true;
          title = "Dunst";
          class = "Dunst";
          startup_notification = true;
          verbosity = "mesg";
          corner_radius = 3;
          ignore_dbusclose = false;
          mouse_left_click = "close_current";
          mouse_middle_click = "do_action, close_current";
          mouse_right_click = "close_all";
        };
      };
    };

    flameshot.enable = true;

    gpg-agent = {
      enable = true;
      enableSshSupport = true;
      defaultCacheTtl = 60;
      defaultCacheTtlSsh = 60;
      maxCacheTtl = 300;
      maxCacheTtlSsh = 300;
      pinentryFlavor = "curses";
    };

    stalonetray = {
      enable = true;
      config = {
        geometry = "3x1-600+0";
        decorations = null;
        icon_size = 30;
        sticky = true;
        background = "#cccccc";
        # display = 0;
      };
    };

  };

  programs = {

    alacritty = {
      enable = true;
      settings = {
        shell.program = "${pkgs.tmux}/bin/tmux";
      };
    };

    autorandr = {
      enable = true;
    };

    bat.enable = true;

    broot.enable = true;

    feh.enable = true;

    firefox.enable = true;

    git = {
      enable = true;
      package = pkgs.gitAndTools.gitFull;
      userName  = "Aniket Deshpande";
      userEmail = "anicake@gmail.com";
      signing = {
        key = "B472EADC3DA53510FDD95E2041FCB7F52CC86EC6";
        signByDefault = true;
      };
      extraConfig = {
        core = {
          editor = "${pkgs.kakoune}/bin/kak";
        };
      };
    };

    gpg.enable = true;

    htop.enable = true;

    i3status-rust = {
      enable = true;
    };

    info.enable = true;

    jq.enable = true;

    kakoune = {
      enable = true;
      config = {
        colorScheme = "gruvbox";
        tabStop = 2;
        indentWidth = 2;
        incrementalSearch = true;
        alignWithTabs = false;
        autoInfo = [ "command" "onkey" ]; # [ "command" "onkey" "normal" ];
        autoComplete = [ "insert" "prompt" ];
        autoReload = "yes"; # [ "yes" "no" "ask" ];
        scrollOff = {
          lines = 2;
          columns = 1;
        };
        ui = {
          setTitle = true;
          statusLine = "top"; # [ "top" "bottom" ];
          assistant = "dilbert"; # [ "clippy" "cat" "dilbert" "none" ];
          enableMouse = true;
          changeColors = true;
          wheelDownButton = null;
          wheelUpButton = null;
          shiftFunctionKeys = null;
          useBuiltinKeyParser = false; # Use the ncurses one
        };
        showMatching = true;
        wrapLines = {
          enable = true;
          word = true;
          indent = true;
          maxWidth = 120;
          marker = "⏎";
        };
        numberLines = {
          enable = true;
          relative = true;
          highlightCursor = true;
          separator = "|";
        };
        showWhitespace = { enable = true; }; # There are a set of default in the module for each whitespace charater to be shown
      };
      extraConfig = ''
        add-highlighter global/number-lines number-lines -separator | # Second set of line-numbers that are not relative
      '';
      plugins = with pkgs.kakounePlugins; [
        kak-fzf
        kak-buffers
        kak-auto-pairs
      ];
    };

    lsd = {
      enable = true;
      enableAliases = true;
    };

    man.enable = true;

    nushell = {
      enable = true;
      settings = {
        edit_mode = "vi";
      };
    };

    rofi = {
      enable = true;
      extraConfig = {
        modi = "window,run,ssh,windowcd,drun,combi,keys,file-browser";
      };
    };

    skim.enable = true;

    starship.enable = true;

    tmux = {
      enable = true;
      aggressiveResize = true;
      customPaneNavigationAndResize = true;
      escapeTime = 0;
      clock24 = true;
      historyLimit = 99999;
      keyMode = "vi";
      terminal = "st-256color";
      sensibleOnTop = true;
      plugins = with pkgs.tmuxPlugins; [
        pain-control
        yank
        copycat
        # sidebar
        # sysstat
        # online-status
        open
        prefix-highlight
      ];
      extraConfig = ''
        # extraConfig

        set -g default-shell "${pkgs.zsh}/bin/zsh"
        set -g mouse on
        set -g monitor-activity on
        set -g renumber-windows on

        bind = set -g synchronize-panes

        # Theme
        set -g status-style "bg=orange,fg=black"
        #set -g window-status-style "bg=black,fg=yellow"

        # Statusline
        set -g status-interval 2
        #set -g status-left-length 0
        #set -g status-right-length 100
        #set -g status-right "| #{prefix_highlight} |"

        # extraConfig.
      '';
    };

    qutebrowser = {
      enable = true;
      searchEngines = {
        DEFAULT = "https://searx.info/sea [...]

2021-06-16 11:32 UTC, ncfavier commented
@aniketd a common pattern is to have `systemctl --user import-environment DISPLAY` (or whatever variables you want to import) somewhere in your `~/.xinitrc`. If you do this before starting dunst, you don't need to restart it.

Also, please don't post large code snippets directly as it makes threads hard to navigate. You can upload them somewhere and link to them, or use a `<details>` tag:

```md
<details>
<summary>My home.nix</summary>

```nix
{
  lorem = "ipsum dolor sit amet";
}
``
</details>
```

2021-06-16 12:37 UTC, aniketd commented
@ncfavier TIL! That's an awesome suggestion, thanks! :slightly_smiling_face:

2021-06-16 12:40 UTC, ncfavier commented
(You need a blank line between `</summary>` and ` ```nix `, for some reason.)

2021-06-16 12:42 UTC, aniketd commented
(Ouch :smile:) :+1: :bow: