xmobar: Add module
nix-community/home-manager pull request #2120
Opened 2021-06-17 22:31 UTC by t4ccer

### Description

Add `xmobar` status bar modue.

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all`.

- [x] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/doc/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [x] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [x] Added myself and the module files to `.github/CODEOWNERS`.

2021-06-18 18:38 UTC, ncfavier requested changes

2021-06-18 18:38 UTC, ncfavier commented on .github/CODEOWNERS
> +/modules/xmobar.nix                                   @t4ccer
This should be `/modules/programs/xmobar.nix`, and you should add `/tests/modules/programs/xmobar`.

The list is ordered alphabetically, but you should group the tests line just after the module line.

2021-06-18 18:38 UTC, ncfavier commented on modules/modules.nix
> +    (loadModule ./programs/xmobar.nix { })
Alphabetically ordered too.

2021-06-18 18:38 UTC, ncfavier commented on modules/programs/xmobar.nix
> +    enable = mkEnableOption "Xmobar: a minimalistic status bar";
I think changing the colon to a comma would read better in context ("Whether to enable Xmobar, a minimalistic status bar").

2021-06-18 18:38 UTC, ncfavier commented on tests/default.nix
> +    ./modules/programs/xmobar
Alphabetically ordered too.

2021-06-18 21:29 UTC, t4ccer commented
Reordered lists to make them alphabetically ordered, and changed colon to a comma in `enable` option description

2021-06-28 06:46 UTC, sumnerevans requested changes
Thanks! Looks good, save a few nits!

2021-06-28 06:46 UTC, sumnerevans commented on .github/CODEOWNERS
> +
nit: remove extra newline

2021-06-28 06:46 UTC, sumnerevans commented on modules/programs/xmobar.nix
> +      default = pkgs.haskellPackages.xmobar;
```suggestion
      default = pkgs.haskellPackages.xmobar;
      defaultText = literalExample "pkgs.haskellPackages.xmobar";
```

2021-06-29 16:33 UTC, sumnerevans requested changes

2021-06-29 16:33 UTC, sumnerevans commented on modules/programs/xmobar.nix
> +        "Extra configuration lines to add to ~/.config/xmobar/.xmobarrc";
sorry for not noticing this on my last review pass

```suggestion
      description = ''
        Extra configuration lines to add to
        <filename>$XDG_CONFIG_HOME/xmobar/.xmobarrc</filename>.
        See
        <link xlink:href="LINK_TO_DOCS" />
        for options.
      '';
```

2021-06-29 19:02 UTC, sumnerevans approved these changes
Checked the docs and it looks good. Thanks for the contribution!

2021-06-29 19:02 UTC, merged