qutebrowser: add onChange ipc reloading
nix-community/home-manager pull request #2168
Opened 2021-07-09 03:49 UTC by Misterio77

### Description

Add a `onChange` entry for qutebrowser, allowing it to react to configuration changes.

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/doc/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

Here's how it looks:

https://user-images.githubusercontent.com/5727578/125020477-49cad580-e04f-11eb-8d61-0ea1a1cb333e.mp4
    
    
I was using something similar to [this script](https://github.com/qutebrowser/qutebrowser/blob/master/scripts/open_url_in_instance.sh) to update my qutebrowser instance when changing themes. I noticed home-manager [automatically reloads sway](https://github.com/nix-community/home-manager/blob/master/modules/services/window-managers/i3-sway/sway.nix#L435) when needed, so i tried to get it working for qutebrowser too.

A few points:
- I'm not sure if tests can even be written for something like this, but i'd be glad to if someone pointed me in the right direction.
- I'm also not sure whether MacOS defines these variables, so i'm not sure if it runs on anything other than Linux, so i added it specifically to the entry inside `hostPlatform.isLinux`. If anyone reading has a Mac, please feel free to paste that into the `hostPlatform.isDarwin` section and try it out.
- Is `${pkgs.coreutils}` needed for stuff such as `echo`? I thought it was, so used it that way. Open to suggestions if that's not the usual way to do it.

I have something of a itch to dynamically theme the entire system through home-manager, so i'll probably open PRs for other programs as i figure them out.

2021-07-10 22:14 UTC, berbiche requested changes
Thanks!

2021-07-10 22:14 UTC, berbiche commented on modules/programs/qutebrowser.nix
> +          hash="$(${pkgs.coreutils}/bin/echo -n $USER | ${pkgs.coreutils}/bin/md5sum | ${pkgs.coreutils}/bin/cut -d' ' -f1)"
```suggestion
          hash="$(echo -n \"$USER\" | ${pkgs.coreutils}/bin/md5sum | ${pkgs.coreutils}/bin/cut -d' ' -f1)"
```

The default shell used in scripts is defined by `pkgs.stdenv.shell` (bash globally).
AFAIK changing the default shell will incur a global rebuild.
This doesn't mean we can use and rely on bashism.

On a second note, popular shells like zsh, ksh, bash and fish all implement echo as a builtin command.

2021-07-10 22:14 UTC, berbiche commented on modules/programs/qutebrowser.nix
> +            ${pkgs.coreutils}/bin/echo "Reloading qutebrowser"
```suggestion
            echo "Reloading qutebrowser"
```

2021-07-10 22:14 UTC, berbiche commented on modules/programs/qutebrowser.nix
> +            $DRY_RUN_CMD ${pkgs.coreutils}/bin/printf '{"args": [":config-source"], "target_arg": null, "protocol_version": 1}\n' | ${pkgs.socat}/bin/socat -lf /dev/null - UNIX-CONNECT:"''${socket}"
```suggestion
            $DRY_RUN_CMD echo '{"args": [":config-source"], "target_arg": null, "protocol_version": 1}' | ${pkgs.socat}/bin/socat -lf /dev/null - UNIX-CONNECT:"''${socket}"
```

`printf` is also a shell builtin in many shells.

You can optionally replace the json with `escapeShellArg (builtins.toJSON { args = [ ":config-source" ]; target_arg = null; protocol_version = 1 })`.
Just thought you'd  be interested in this neat trick!

2021-07-10 23:18 UTC, Misterio77 commented
@berbiche, thanks a lot for the review and suggestions.

It seems `$USER` has to be unquoted, or else i get the wrong md5 hash. Just fixed this in the last commit

I got `toJSON` working, but it seems the JSON keys and strings don't get quoted, unless i escape a double quote inside the already existing quote (quite ugly), and qutebrowser won't accept the command if they're not.

I wonder if there's any better way to do it?
```bash
command=${builtins.toJSON { "\"args\"" = [ "\":config-source\"" ]; "\"target_arg\"" = null; "\"protocol_version\"" = 1; }}
$DRY_RUN_CMD echo $command | ${pkgs.socat}/bin/socat -lf /dev/null - UNIX-CONNECT:$socket
```

2021-07-10 23:58 UTC, Misterio77 commented
Oooh that's what the `escapeShellArg` is for, got it working now.

2021-07-11 07:26 UTC, rycee commented on modules/programs/qutebrowser.nix
> +          hash="$(echo -n $USER | ${pkgs.coreutils}/bin/md5sum | ${pkgs.coreutils}/bin/cut -d' ' -f1)"
The coreutils package is in path:

```suggestion
          hash="$(echo -n $USER | md5sum | cut -d' ' -f1)"
```

2021-07-11 07:28 UTC, rycee commented on modules/programs/qutebrowser.nix
> +        '';
When introducing variables in an activation block then it is best to make sure they are removed after use:
```suggestion
          unset hash socket command
        '';
```

2021-07-11 07:37 UTC, rycee commented
Looks good I think, just some minor comments. Btw, you'll need to run the format script in the project root.

2021-07-11 13:35 UTC, Misterio77 commented
Thanks for the help, @rycee!

Should i squash my commits?

2021-07-11 20:54 UTC, merged

2021-07-11 20:55 UTC, rycee commented
@Misterio77 No need, I've squashed and merged now :-)