gh: add options for "pager" and "prompt" to gh.nix
nix-community/home-manager pull request #2232
Opened 2021-07-29 15:49 UTC by JackMoffat

### Description

These two options are present in the config.yml file generated by
"gh auth login" with browser authentication. This change allows
gh.nix to generate a config.yml file that includes these options.

### Checklist

- [ ] Change is backwards compatible.

- [ ] Code formatted with `./format`.

- [ ] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [ ] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/doc/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

2021-07-30 16:47 UTC, sumnerevans requested changes
Thanks for the contribution! Added some notes.

2021-07-30 16:47 UTC, sumnerevans commented on modules/programs/gh.nix
> +        '';
```suggestion
      description = ''
        When to interactively prompt.
        This is a global config that cannot be overridden by hostname.
        Supported values: enabled, disabled.
      '';
```

2021-07-30 16:47 UTC, sumnerevans commented on modules/programs/gh.nix
> +      type = types.enum [ "enabled" "disabled" ];
Maybe just make this a boolean?

2021-07-30 16:47 UTC, sumnerevans commented on modules/programs/gh.nix
> +    };
```suggestion
    pager = mkOption {
      type = types.str;
      default = "";
      example = "less";
      description = ''
        The pager program to send command output to.
        Set the value to <literal>"cat"</literal> to disable the pager.
      '';
    };
```

2021-07-30 16:47 UTC, sumnerevans commented on modules/programs/gh.nix
> +        When to interactively prompt.
```suggestion
        Whether to interactively prompt.
```

2021-07-30 16:47 UTC, sumnerevans commented on modules/programs/gh.nix
> +        Supported values: enabled, disabled.
I'm pretty sure the options should already be rendered in the docs.

```suggestion
```

2022-01-19 22:16 UTC, berbiche commented
Closing per my former comments: https://github.com/nix-community/home-manager/pull/2232#issuecomment-948925186

2022-01-19 22:16 UTC, closed without merging