glow: add glow to home-manager
nix-community/home-manager pull request #2332
Opened 2021-09-17 07:17 UTC by geowy

Add Glow, a terminal-based markdown reader.

### Description

Add Glow, a terminal-based markdown reader.

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all`.

- [x] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [x] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [x] Added myself and the module files to `.github/CODEOWNERS`.

2021-09-20 15:10 UTC, sumnerevans commented
Please split this into two PRs.

2021-09-24 09:51 UTC, geowy commented
@sumnerevans thanks, changes have been made.

Second PR is here and still draft: https://github.com/nix-community/home-manager/pull/2346

2021-09-24 17:02 UTC, sumnerevans requested changes

2021-09-24 17:02 UTC, sumnerevans commented on modules/programs/glow.nix
> +  ];
I don't think you need the `mkMerge`. Also, use `yamlFormat.generate`

```suggestion
  config = mkIf cfg.enable {
    home.packages = [ pkgs.glow ];

    home.file."Library/Preferences/glow/glow.yml" =
      mkIf (cfg.settings != { } && isDarwin) {
        text = yamlFormat.generate cfg.settings;
      };

    xdg.configFile."glow/glow.yml" = mkIf (cfg.settings != { } && !isDarwin) {
      text = yamlFormat.generate cfg.settings;
    };
  };
```

2022-01-11 16:17 UTC, closed without merging

2023-11-30 10:42 UTC, terlar commented
Just found myself looking for this today. I guess you don't plan to continue with this @geowy, if not I guess I might take a stab at it myself