Provide path option for dircolors
nix-community/home-manager pull request #2349
Opened 2021-09-27 11:10 UTC by winston0410

### Description

Add path option for dircolors, allowing user to change its location for XDG compliance

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all`.

- [] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [ ] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

2021-09-27 13:25 UTC, sumnerevans requested changes

2021-09-27 13:25 UTC, sumnerevans commented on modules/programs/dircolors.nix
> +      type = types.str;
```suggestion
      type = types.path;
```

2021-09-27 15:55 UTC, winston0410 commented on modules/programs/dircolors.nix
> +      eval $(${pkgs.coreutils}/bin/dircolors -b ${cfg.path})
Right I have forgotten that. thanks!

2021-09-27 17:24 UTC, sumnerevans requested changes
Please also make your commit messages match the contributing guidelines: https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#commits

2021-09-27 17:24 UTC, sumnerevans commented on modules/programs/dircolors.nix
> +    home.file.${cfg.path}.text = concatStringsSep "\n" ([ ]
It would be good to add a test to this to make sure that it's putting the file in the correct place.

2021-09-27 22:49 UTC, rycee commented
An alternative is perhaps to do something like

```patch
diff --git a/modules/programs/dircolors.nix b/modules/programs/dircolors.nix
index 6ac16da5..faf7fe4e 100644
--- a/modules/programs/dircolors.nix
+++ b/modules/programs/dircolors.nix
@@ -6,6 +6,11 @@ let
   cfg = config.programs.dircolors;
 
   formatLine = n: v: "${n} ${toString v}";
+
+  configFile = pkgs.writeText "dircolors" (concatStringsSep "\n" ([ ]
+    ++ mapAttrsToList formatLine cfg.settings ++ [ "" ]
+    ++ optional (cfg.extraConfig != "") cfg.extraConfig));
+
 in {
   meta.maintainers = [ hm.maintainers.justinlovinger ];
 
@@ -203,21 +208,17 @@ in {
       ".xspf" = mkDefault "00;36";
     };
 
-    home.file.".dir_colors".text = concatStringsSep "\n" ([ ]
-      ++ mapAttrsToList formatLine cfg.settings ++ [ "" ]
-      ++ optional (cfg.extraConfig != "") cfg.extraConfig);
-
     programs.bash.initExtra = mkIf cfg.enableBashIntegration ''
-      eval $(${pkgs.coreutils}/bin/dircolors -b ~/.dir_colors)
+      eval $(${pkgs.coreutils}/bin/dircolors -b ${configFile})
     '';
 
     programs.fish.shellInit = mkIf cfg.enableFishIntegration ''
-      eval (${pkgs.coreutils}/bin/dircolors -c ~/.dir_colors)
+      eval (${pkgs.coreutils}/bin/dircolors -c ${configFile})
     '';
 
     # Set `LS_COLORS` before Oh My Zsh and `initExtra`.
     programs.zsh.initExtraBeforeCompInit = mkIf cfg.enableZshIntegration ''
-      eval $(${pkgs.coreutils}/bin/dircolors -b ~/.dir_colors)
+      eval $(${pkgs.coreutils}/bin/dircolors -b ${configFile})
     '';
   };
 }
```

Then there is no need for a `dir_colors` file at all in `$HOME`. Or perhaps the file is used in other places than shells?

2021-09-28 05:17 UTC, winston0410 commented
@rycee That will do and it is better i think, I guess it just have to be supplied to `coreutils` for setting `LS_COLOR`.

2022-01-03 07:09 UTC, closed without merging