emacs: allow adding command-line arguments to the emacs daemon.
nix-community/home-manager pull request #2356
Opened 2021-09-29 14:06 UTC by schotts-fired

### Description

### Checklist

- [ x ] Change is backwards compatible.

- [ x ] Code formatted with `./format`.

- [ ] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [ x ] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

2021-09-29 21:25 UTC, sumnerevans approved these changes

2021-09-29 21:28 UTC, sumnerevans requested changes
Please update the failing tests and add a new one that tests this new functionality.

2021-09-30 09:06 UTC, schotts-fired commented
Sorry if the force push messed something up I am pretty new to this.
I have updated the test cases. I also thought it might be better to add the tests for the new functionality to the existing test cases because otherwise the tests with and without would be pretty much identical.

2021-10-02 06:54 UTC, rycee commented on modules/services/emacs.nix
> +    arguments = mkOption {
This kind of option is typically called `extraOptions`. For example, see
https://github.com/nix-community/home-manager/blob/d5151186aca3d706be73b02f47cff574cb91c641/modules/services/fluidsynth.nix#L33-L43
```suggestion
    extraOptions = mkOption {
```

2021-10-02 06:54 UTC, rycee commented on modules/services/emacs.nix
> +            } ${concatStringsSep " " cfg.arguments}"
```suggestion
            } ${escapeShellArgs cfg.arguments}"
```

2021-10-02 06:55 UTC, rycee commented
Looks good, just added two minor comments.

2021-10-02 23:01 UTC, merged

2021-10-02 23:01 UTC, rycee commented
Thanks! Merged to master.