tint2: add module
nix-community/home-manager pull request #2574
Opened 2021-12-17 16:01 UTC by CarlosLoboxyz

### Description

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [ ] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [x] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [x] Added myself and the module files to `.github/CODEOWNERS`.

2021-12-23 22:18 UTC, berbiche requested changes
Thanks for the PR.

Tint2's settings format seems to be a plain ini file.
Could you add a `settings` option and rename the `config` option to `extraConfig`?

Ideally, the tint2 module should look like the Mercurial one: https://github.com/nix-community/home-manager/blob/4fa1ba72a39da509399cce43995e4c1e1960ce9c/modules/programs/mercurial.nix
That is, it should have a `package`, `settings` and `extraConfig` option.

The module should also declare a systemd service (maybe with an `enable` option?) that will automatically start tint2.

2021-12-30 11:08 UTC, CarlosLoboxyz commented
Not sure how test the systemd unit since I'm running xorg using xinit, which means i've to star my user user units manually

2022-01-09 22:14 UTC, berbiche reviewed
You don't need to test the tint2 systemd service if you cannot do it on your system.

2022-01-09 22:14 UTC, berbiche commented on modules/programs/tint2.nix
> +  meta.maintainers = with maintainers; [ CarlosLoboxyz ];
```suggestion
  meta.maintainers = [ hm.maintainers.CarlosLoboxyz ];
```

2022-01-22 17:27 UTC, merged

2022-01-22 17:28 UTC, rycee commented
I made a few minor cleanups and merged to master. I agree that this module really should be a service one and not a program one, hopefully somebody comes along in the future and does the conversion. Can do a `mkRenamedOptionModule` when that happens.