watson: add module
nix-community/home-manager pull request #2602
Opened 2022-01-01 23:34 UTC by polykernel

Watson is a CLI for tracking your time.

Two unit tests were added to validate the module behavior for
an empty configuration and the example configuration.

### Description

### Checklist

- [ ] Change is backwards compatible.

- [ ] Code formatted with `./format`.

- [ ] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [ ] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

2022-01-02 07:25 UTC, sumnerevans requested changes

2022-01-02 07:25 UTC, sumnerevans commented on modules/programs/watson.nix
> +      '';
```suggestion
      enable = mkEnableOption "watson, a CLI to track your time'';
```

2022-01-02 07:25 UTC, sumnerevans commented on modules/programs/watson.nix
> +      };
these should use `mkEnableOption`:

```suggestion
      enableBashIntegration = mkEnableOption "watson's bash integration" // {
        default = true;
      };

      enableZshIntegration = mkEnableOption "watson's zsh integration" // {
        default = true;
      };

      enableFishIntegration = mkEnableOption "watson's fish integration" // {
        default = true;
      };
```

2022-01-09 21:52 UTC, berbiche requested changes
Thanks.

Found additional nitpicks.

2022-01-09 21:52 UTC, berbiche commented on modules/programs/watson.nix
> +  configDir = if pkgs.stdenv.isDarwin then
```suggestion
  configDir = if pkgs.stdenv.hostPlatform.isDarwin then
```

2022-01-09 21:52 UTC, berbiche commented on modules/programs/watson.nix
> +      enable = mkEnableOption "watson, a wonderful CLI to track your time!";
```suggestion
      enable = mkEnableOption "watson, a wonderful CLI to track your time";
```
A period is automatically appended.

2022-01-09 23:18 UTC, polykernel commented on modules/programs/watson.nix
> +  configDir = if pkgs.stdenv.isDarwin then
thanks! I have also updated the tests.

2022-01-09 23:18 UTC, polykernel commented on modules/programs/watson.nix
> +      enable = mkEnableOption "watson, a wonderful CLI to track your time!";
thanks!

2022-01-10 03:37 UTC, berbiche approved these changes
LGTM!

ping @sumnerevans

2022-01-22 15:30 UTC, merged