plex-mpv-shim: init service
nix-community/home-manager pull request #2655
Opened 2022-01-20 23:57 UTC by starcraft66

### Description

Adds a home-manager module to create a config file and run a systemd user service for [plex-mpv-shim](https://github.com/iwalton3/plex-mpv-shim)

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [x] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [x] Added myself and the module files to `.github/CODEOWNERS`.

2022-01-25 17:25 UTC, starcraft66 commented
So that it can always be running and that you don't have to open it every time you want to watch something...

2022-02-02 20:39 UTC, berbiche requested changes
Thanks for the PR!

Should the package be added to `home.packages`?

2022-02-02 20:39 UTC, berbiche commented on modules/services/plex-mpv-shim.nix
> +  options = {
```suggestion
in {
  meta.maintainers = [ maintainers.starcraft66 ];
  
  options = {
```

2022-02-02 21:06 UTC, starcraft66 commented on modules/lib/maintainers.nix
> +  };
okay

2022-02-02 21:07 UTC, starcraft66 commented on modules/services/plex-mpv-shim.nix
> +  options = {
oops

2022-02-02 21:08 UTC, starcraft66 commented
I don't think it's useful for the package to be in `home.packages`, it doesn't have any cli options other than `--config` and just starts the program.

2022-02-02 21:33 UTC, berbiche approved these changes

2022-02-02 21:34 UTC, merged