kitty: add option `theme`
nix-community/home-manager pull request #2710
Opened 2022-02-08 16:58 UTC by NelsonJeppesen

### Description
Add a new option to use the recently added `kitty-themes` nix package to set the theme. Use the friendly name of the theme seen in `kitty +kitten themes` 

https://github.com/kovidgoyal/kitty-themes

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).
The current test for kitty is a simple match against a example file. Because this change adds a path to the nix store, that will no longer work because the path can change. I'm not sure if it's worth re-writing all the kitty tests just to cover themes

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

2022-02-08 17:49 UTC, sumnerevans requested changes

2022-02-08 17:49 UTC, sumnerevans commented on modules/programs/kitty.nix
> +        for more details
```suggestion
        for more details.
```

2022-02-08 17:49 UTC, sumnerevans commented on modules/programs/kitty.nix
> +        any theme given by the command <literal>kitty +kitten themes</literal>.
```suggestion
        any theme given by the command <command>kitty +kitten themes</command>.
```

2022-02-08 18:39 UTC, sumnerevans approved these changes

2022-02-08 18:54 UTC, merged

2022-03-01 13:59 UTC, kryachkov commented
Fails with
```
error: attribute 'kitty-themes' missing, at /home/andfalk/.nix-defexpr/channels/home-manager/modules/programs/kitty.nix:146:21
```

when I add `theme = "Solarized Light";` to my `home.nix`. Any ideas how to fix?

2022-03-01 14:01 UTC, NelsonJeppesen commented
> Fails with
> ```
> error: attribute 'kitty-themes' missing, at /home/andfalk/.nix-defexpr/channels/home-manager/modules/programs/kitty.nix:146:21
> ```
> 
> when I add `theme = "Solarized Light";` to my `home.nix`. Any ideas how to fix?
> 

I believe kitty themes is only on NixOS unstable but will be available when 22.05 comes out. Are you running unstable or 21.11?

2022-03-02 12:34 UTC, kryachkov commented
Yaha, correct, I'm on 21.11. Will wait for 22.05 release then. Thanks