modules/default.nix: Add useNixpkgsModule parameter
nix-community/home-manager pull request #2720
Opened 2022-02-13 20:06 UTC by LunNova

### Description

Fixes #2701 by making it possible to disable the nixpkgs module with the unprivileged flake setup.

I also made this the default for `lib.homeManagerConfiguration` as I think it makes more sense for performance to use the `pkgs` input directly rather than reimporting it and copying config/overlays. I could change that back to being optional if desired, not sure.

The current requirement that `homeManagerConfiguration` take a `stateVersion`, `homeDirectory` and `username` arg feels weird to me as it prevents setting these in that user's configuration nix files (unless you mkForce). This is more often done this way and makes it easier to share the same configuration between use in nixos modules and use for the unprivileged flake setup.

I think it would be best if `homeManagerConfiguration` worked like this:

```
      homeManagerConfiguration = { configuration, system
          , extraModules ? [ ], extraSpecialArgs ? { }
          , pkgs ? builtins.getAttr system nixpkgs.outputs.legacyPackages
          , check ? true }@args:
          import ./modules {
            inherit pkgs check extraSpecialArgs useNixpkgsModule;
            configuration = { ... }: {
              imports = [ configuration ] ++ extraModules;
              // removed the home.* settings here and removed the args for them
              // they should be set in extraModules or configuration like all other hm config is
            };
          };
      };
```

But that wouldn't be backwards compatible. 

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

2022-02-20 04:10 UTC, berbiche requested changes
Would it be possible to update the flake document in the README and the manuals to mention this new option?

2022-02-20 04:10 UTC, berbiche commented on flake.nix
> +          , check ? true, stateVersion ? "20.09", useNixpkgsModule ? false
```suggestion
          , check ? true, stateVersion ? "20.09", useNixpkgsModule ? true
```

Let's toggle this to false by default for the sake of backward compatibility.

2022-05-07 18:07 UTC, LunNova commented
Reverted the flake.nix change, let's just add the extra flag to `modules/default.nix` since it's easy enough to write your own thing which imports it and I wasn't sure how to handle documentation/backcompat.

This should still be an improvement even if it's not as easy to use.

2022-07-19 16:58 UTC, LunNova commented
@rycee @berbiche is there anything I need to do to get this merged?

Most of what I wanted to do was done in #3037 (by just not being back compat which is cool), the only change left in this PR is adding a `useNixpkgsModule` option in `modules/default.nix` and it should be ready.

2022-07-25 17:24 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/nixpkgs-unfree-configs-not-respected/20546/10

2022-08-14 22:33 UTC, berbiche commented
Hi, sorry, this PR is ready to be merged but it would be great if the documentation mentioned this new option.

2022-08-14 22:43 UTC, LunNova commented
Doesn't look like there is anywhere to document it with the current structure. If you use the CLI you don't import this yourself so it's not exposed, similarly if you use the flake.nix lib.homeManagerConfiguration it's not exposed yet.

I could add it as an option to that and document it, although I was trying to keep this minimal so I could get it merged :thinking:

2022-08-15 03:40 UTC, LunNova commented
@berbiche added the option to `lib.homeManagerConfiguration` so it's exposed and documented it. I defaulted it to `true`, happy to swap that to `false` if that's preferred.

2022-08-15 04:01 UTC, LunNova commented
1 failing test in CI, it's also failing on master.

2022-08-17 04:33 UTC, berbiche approved these changes
I'd like your input on this @rycee when you can :slightly_smiling_face:

2022-08-17 04:33 UTC, berbiche commented on modules/default.nix
> +, useNixpkgsModule ? true
I agree that setting this to `true` is the better choice, but I am sure there will be bug tickets related to this change.

2022-08-17 04:33 UTC, berbiche commented
> 1 failing test in CI, it's also failing on master.

This has been resolved on master

2023-05-19 11:11 UTC, ncfavier commented on flake.nix
> +          , extraSpecialArgs ? { }, check ? true, disableNixpkgsModule ? true
Why the negation? `useNixpkgsModule`. Also it should default to whatever its value is now, to preserve backwards compatibility.

2023-05-19 20:16 UTC, LunNova commented
I don't have the energy to update this right now. I did more than a year ago when I opened it but it's taken so long going through reviews that it doesn't feel worth it.

Hopefully someone else can make a PR for this.

2023-05-19 20:16 UTC, closed without merging

2023-12-01 12:29 UTC, nhooey commented
I created this StackOverflow question to help everyone figure this out for the various different scenarios of using Nix:

* [StackOverflow: How to allow "unfree" packages in Nix, for each situation?: {NixOS, Nix, Nix with Flakes, Nix with Flakes and Home Manager}](https://stackoverflow.com/questions/77585228/how-to-allow-unfree-packages-in-nix-for-each-situation-nixos-nix-nix-wit)

Since GitHub issue comments are structured more like a forum of endless posts sorted by time instead of a proper question & answer site.