just: add module for the just command runner
nix-community/home-manager pull request #2734
Opened 2022-02-19 01:11 UTC by maximsmol

### Description

Adds a module for [just](https://github.com/casey/just) and its shell completions.

### Checklist

- [X] Change is backwards compatible.

- [X] Code formatted with `./format`.

- [X] Code tested through `nix-shell --pure tests -A run.all`.

- [X] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [X] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [X] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [X] Added myself and the module files to `.github/CODEOWNERS`.

2022-02-20 03:38 UTC, berbiche requested changes
Thanks for the contribution!

2022-02-20 03:38 UTC, berbiche commented on .github/CODEOWNERS
> +/modules/programs/just.nix                            @maximsmol
Could this be moved at the right place to preserve the ordering? Thanks.

2022-02-20 03:38 UTC, berbiche commented on modules/programs/just.nix
> +  meta.maintainers = [ maintainers.maximsmol ];
```suggestion
  meta.maintainers = [ hm.maintainers.maximsmol ];
```

Home Manager's maintainers are available `lib.hm.maintainers`.

2022-02-20 03:38 UTC, berbiche commented on modules/programs/just.nix
> +      "just is a handy way to save and run project-specific commands";
This expands to `Whether to enable just is a handy way...`.
The phrasing seems odd.

2022-02-21 02:31 UTC, sumnerevans commented on modules/programs/just.nix
> +      "just - a handy way to save and run project-specific commands";
```suggestion
      "just, a handy way to save and run project-specific commands";
```

2022-02-21 02:31 UTC, sumnerevans commented on modules/programs/just.nix
> +    };
All of these enable options can use `mkEnableOption` like so:

```suggestion
    enableBashIntegration = mkEnableOption "Bash integration" // {
      default = true;
    };
```

2022-02-21 05:38 UTC, maximsmol commented
@sumnerevans just fyi, copied both the description style ("{name} - {description}") and the `mkOption` from `programs.fzf`—I could reformat those in another PR according to your suggestions as well if you think it'd be good

2022-02-26 23:58 UTC, berbiche approved these changes
LGTM!

2022-02-27 00:17 UTC, berbiche commented
Your PR needs to be rebased on "master" to include a fix that will allow the checks to succeed.

2022-03-06 09:08 UTC, merged

2022-03-06 09:09 UTC, rycee commented
Merged to master now. Thanks!