waybar: fix command not found when reloading
nix-community/home-manager pull request #2865
Opened 2022-04-05 18:45 UTC by danth

### Description

Currently, trying to run `systemctl --user reload waybar.service` fails with:

```
Apr 05 19:31:39 StarBook-MkV systemd[2313]: Reloading Highly customizable Wayland bar for Sway and Wlroots based compositors....
Apr 05 19:31:39 StarBook-MkV systemd[46289]: waybar.service: Failed to locate executable kill: No such file or directory
Apr 05 19:31:39 StarBook-MkV systemd[46289]: waybar.service: Failed at step EXEC spawning kill: No such file or directory
Apr 05 19:31:39 StarBook-MkV systemd[2313]: waybar.service: Control process exited, code=exited, status=203/EXEC
Apr 05 19:31:39 StarBook-MkV systemd[2313]: Reload failed for Highly customizable Wayland bar for Sway and Wlroots based compositors..
```

Fixed this by inserting the full path to the `kill` command from the `busybox` package.

### Checklist

- [x] Change is backwards compatible.

- [ ] Code formatted with `./format`.

- [ ] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- [x] (Extra:) Code tested on a live system.

2022-04-05 21:17 UTC, berbiche requested changes
Thanks!

2022-04-05 21:17 UTC, berbiche commented on modules/programs/waybar.nix
> +          ExecReload = "${pkgs.busybox}/bin/kill -SIGUSR2 $MAINPID";
```suggestion
          ExecReload = "${pkgs.coreutils}/bin/kill -SIGUSR2 $MAINPID";
```

2022-04-07 05:41 UTC, berbiche commented
Once #2867 is merged, you will have to rebase your changes to fix the failing tests.
I am unable to merge a PR with failing tests.

2022-04-08 09:55 UTC, danth commented
@berbiche Sorry for the delay, I've rebased the changes now :smile:

2022-04-08 15:34 UTC, sumnerevans approved these changes

2022-04-08 15:58 UTC, sumnerevans commented
Looks like the test needs to be fixed. It also needs `test.stubs.coreutils = { }`

2022-04-08 17:58 UTC, berbiche commented
> Looks like the test needs to be fixed. It also needs `test.stubs.coreutils = { }`

:+1: though coreutils is very likely already part of the test closure.

2022-04-10 10:33 UTC, danth commented
@sumnerevans `test.stubs.coreutils` causes an infinite recursion. What would you suggest I do?

2022-04-11 01:51 UTC, berbiche commented
> @sumnerevans `test.stubs.coreutils` causes an infinite recursion. What would you suggest I do?

In that case, there's no need for a stub 👍

2022-04-11 09:29 UTC, danth commented
Used `normaliseStorePaths` instead of a stub; the test should be working now.

2022-04-11 14:18 UTC, berbiche approved these changes

2022-04-11 16:17 UTC, danth commented
Fixed formatting.

2022-04-16 22:31 UTC, merged