nushell: update to reflect new settings style
nix-community/home-manager pull request #2979
Opened 2022-05-24 18:34 UTC by schuelermine

### Description

Updated the nushell module to reflect the current nushell configuration style.

### Checklist

- [ ] Change is backwards compatible.

- [ ] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

2022-05-24 21:23 UTC, sumnerevans requested changes

2022-05-24 21:23 UTC, sumnerevans commented on tests/modules/services/window-managers/sway/sway-no-xwayland.nix
> -                    ''
please remove this change. It seems entirely unrelated

2022-05-24 21:31 UTC, sumnerevans commented on modules/programs/nushell.nix
> +      defaultText = literalExpression ''""'';
I don't think `defaultText` isn't necessary for default-empty strings (at least I can't find another instance of that in the repo.

2022-05-25 06:24 UTC, rycee commented
Seems like a duplicate of #2957.

2022-07-17 15:24 UTC, rycee commented
I believe this is fixed since the merge of the PR mentioned previously.

2022-07-17 15:24 UTC, closed without merging