fusuma: fix settings example
nix-community/home-manager pull request #3067
Opened 2022-07-02 08:59 UTC by juboba

### Description

The example for settings is including the top level options, which is misleading.

### Checklist

- [x] Change is backwards compatible.

- [ ] Code formatted with `./format`.

- [ ] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

2022-07-02 16:24 UTC, sumnerevans requested changes

2022-07-02 16:24 UTC, sumnerevans commented on modules/services/fusuma.nix
> +        config = {
```suggestion
        {
```

2022-07-03 11:07 UTC, juboba commented on modules/services/fusuma.nix
> +        config = {
@sumnerevans totally right, thanks!

2022-07-06 16:21 UTC, berbiche approved these changes
LGTM!

2022-07-07 06:22 UTC, sumnerevans approved these changes

2022-07-07 06:22 UTC, sumnerevans commented
@juboba please rebase on the latest `master`. The build is already fixed there.

2022-07-07 06:55 UTC, merged

2022-07-07 06:55 UTC, sumnerevans commented
Thanks for the contribution!