zsh: add option for `zsh-history-substring-search`
nix-community/home-manager pull request #3156
Opened 2022-08-19 08:17 UTC by CardboardTurkey

### Description

Add an option for installing [zsh-history-substring-search](https://github.com/zsh-users/zsh-history-substring-search).

I added it as a submodule of `zsh` but perhaps it would make more sense within the `zsh.history` module?

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

2022-08-19 17:47 UTC, berbiche requested changes
Thanks for the contribution.

I don't know zsh and this module well enough to have an informed opinion but the addition does not feel substantive to me.

2022-08-19 17:47 UTC, berbiche commented on modules/programs/zsh.nix
> +        ${optionalString cfg.historySubstringSearch.enable
The default value for `historySubstringSearch` is an empty attribute set so the `enable` does not always exist.
```suggestion
        ${optionalString (cfg.historySubstringSearch.enable or false)
```

2022-08-19 17:47 UTC, berbiche commented on modules/programs/zsh.nix
> +        type = types.listOf types.str;
Can you split this option?
Using a list is opaque for this sort of option and does not work well if you want to override only one keybind.
It also leads to weird logic like the `elemAt` in the `config` section.

2022-08-23 21:23 UTC, CardboardTurkey commented
Thanks a lot for the review! Changes implemented.

> the addition does not feel substantive to me

I don't think I understand what you mean by substantive here. Note the substring package has to be activated _after_ the syntax-highlighting one. Without this PR I don't see how a user can use both packages and also achieve this.

2022-08-25 19:03 UTC, berbiche commented
> Note the substring package has to be activated _after_ the syntax-highlighting one. Without this PR I don't see how a user can use both packages and also achieve this

Thanks for the explanation 👍

2022-08-25 19:22 UTC, berbiche requested changes
Small nits

2022-08-25 19:22 UTC, berbiche commented on modules/programs/zsh.nix
> +          The default of ^[[A corresponds to the UP key.
```suggestion
          The default of <literal>^[[A</literal> corresponds to the UP key.
```

2022-08-25 19:22 UTC, berbiche commented on modules/programs/zsh.nix
> +          The default of ^[[B corresponds to the DOWN key.
```suggestion
          The default of <literal>^[[B</literal> corresponds to the DOWN key.
```

2022-08-26 17:48 UTC, berbiche approved these changes
Sorry, I also missed this, otherwise lgtm.

2022-08-26 17:48 UTC, berbiche commented on modules/programs/zsh.nix
> +      enable = mkEnableOption "enable";
```suggestion
      enable = mkEnableOption "history substring search";
```

2022-08-31 12:35 UTC, CardboardTurkey commented
Fix applied!

2022-09-05 17:17 UTC, sumnerevans approved these changes

2022-09-13 10:42 UTC, CardboardTurkey commented
Is there anything blocking this being merged?

2022-09-13 20:06 UTC, merged

2022-09-13 20:06 UTC, berbiche commented
Sorry, thanks again!