tmux mouse support
nix-community/home-manager pull request #3158
Opened 2022-08-19 13:02 UTC by cor

### Description

Allows you to enable mouse support in tmux

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all`.

- [x] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

2022-08-19 17:35 UTC, berbiche requested changes
Thanks for the contribution!

2022-08-19 17:35 UTC, berbiche commented on modules/programs/tmux.nix
> +      };
This can be simplified:
```suggestion
      mouse = mkEnableOption "mouse support";
```

2022-08-20 07:18 UTC, cor commented on modules/programs/tmux.nix
> +      };
Ah this is much nicer, thanks!

2022-08-24 20:36 UTC, berbiche commented
Hi,
Can you update the tmux tests to reflect your change?
Thanks

2023-02-05 10:02 UTC, closed without merging