programs.neovim: default to init.lua
nix-community/home-manager pull request #3233
Opened 2022-09-17 22:06 UTC by teto

We change the current logic: instead of writing an init.vim which loads lua/init-home-manager.lua, we write an init.lua that sources init.vim

This commit also avoids writing any of these files if the plugins have no config.

Should fix https://github.com/nix-community/home-manager/issues/1907

### Description

### Checklist

- [ ] Change is backwards compatible.

- [ ] Code formatted with `./format`.

- [ ] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [ ] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

2022-09-17 22:06 UTC, teto commented on modules/programs/neovim.nix
> +            + lib.optionalString hasLuaConfig "vim.cmd([[source ~/.config/nvim/init.vim]])";
of course this needs to be adapted.

2022-09-18 01:45 UTC, AndersonTorres requested changes
`./format` the code

2022-09-18 22:28 UTC, AndersonTorres approved these changes

2022-09-19 07:39 UTC, ambroisie approved these changes

2022-09-21 19:36 UTC, johanneshorner commented
Using these commits with only "programs.neovim.enable = true" does create an empty "init.lua" file for me. Thats not correct right?
The file should only be created if "extraConfig" or some other config options are set. Except maybe I'm missing some default option I'd have to set?

2022-09-21 22:05 UTC, teto commented
@johanneshorner thanks that's exactly the kind of feedback I was looking for. I've adjusted the test to check that. Should be good now

2022-09-22 06:11 UTC, johanneshorner commented
@teto Just retested with the new commit. Works exactly as described in your pull request now. I can just symlink my full neovim config to "$HOME/.config/nvim" and there are no more conflicts. Thanks for the all the hard work :-).

2022-09-22 08:39 UTC, merged

2022-09-22 09:41 UTC, rycee commented
Nicely done! :+1:

2022-10-16 07:50 UTC, Smaug123 commented
This PR broke my setup on Darwin, https://github.com/Smaug123/nix-dotfiles/blob/server-flake/home.nix#L130 (commit 418bab12b271a0a909778e1b27f0bd0e9e16edb8), and I'm still trying to work out how to fix it. When I start `neovim` now:

```
Error detected while processing /Users/patrick/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /Users/patrick/.config/nvim/init.lua:1: Vim(source):E484: Can't open file /var/empty/.config/nvim/init-home-manager.vim
stack traceback:
        [C]: in function 'cmd'
        /Users/patrick/.config/nvim/init.lua:1: in main chunk
```

If I add the configuration `xdg.configHome = "/Users/patrick"` to make the path correct, neovim does start without errors, but my Git config is no longer picked up. (I'd never heard of XDG before this bug, so I am having to learn a lot of stuff quite quickly now.)

2022-10-21 13:51 UTC, ffung commented
@Smaug123 Not sure if you have resolved this, but this worked for me https://github.com/LnL7/nix-darwin/issues/423#issuecomment-1238515147

2022-10-21 19:51 UTC, Smaug123 commented
> @Smaug123 Not sure if you have resolved this, but this worked for me https://github.com/LnL7/nix-darwin/issues/423#issuecomment-1238515147

No apparent effect, I'm afraid.