batsignal: add module
nix-community/home-manager pull request #3243
Opened 2022-09-20 11:32 UTC by loicreynier

### Description

Adds [batsignal](https://github.com/electrickite/batsignal) module.

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all`.

- [x] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [x] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [x] Added myself and the module files to `.github/CODEOWNERS`.

2022-09-20 11:39 UTC, loicreynier commented
I wanted to add the `dangerLevelCommand` option to the test, but since it generates an entry in the store for the generated shell script I don't know how to deal with it:

```service
[Service]
ExecStart=@batsignal@/bin/batsignal -w 15 -c 5 -d 2 -f 5 -D /nix/store/fv4mq8q355016vraa178bndbqa75w4rx-batsignal-dangercmd -n 'Internal' -m 120 -a 'Batsignal daemon' -I battery
```

2022-11-27 14:36 UTC, loicreynier commented
I fixed the test (typo in expected service config), simplified the package option with `mkPackageOption` and rebased into `master`.

2022-12-01 11:14 UTC, loicreynier commented
I added the `dangerLevelCommand` to the test using `normalizeStorePaths`. I also added all the other options to the test which is now complete.

2023-03-02 15:46 UTC, sumnerevans requested changes
Looks good, overall.

2023-03-02 15:46 UTC, sumnerevans commented on modules/services/batsignal.nix
> +      example = 15;
I think we should line up these defaults with what batsignal does: https://github.com/electrickite/batsignal/blob/master/batsignal.1.in#L34

```suggestion
      default = 15;
      example = 20;
```

2023-03-02 15:46 UTC, sumnerevans commented on modules/services/batsignal.nix
> +      description = "Warning level message.";
I think this lines up a bit better with the man page: https://github.com/electrickite/batsignal/blob/master/batsignal.1.in#L46

(also do the same for all of the other `*LevelMessage` descriptions)

```suggestion
      description = "The message to show when the battery reaches the warning level.";
```

2023-03-02 16:38 UTC, loicreynier commented
Thanks for the review @sumnerevans, I changed what your requested.

2023-03-20 11:58 UTC, closed without merging