qutebrowser: add greasemonkey userscript option
nix-community/home-manager pull request #3301
Opened 2022-10-04 19:50 UTC by IvarWithoutBones

### Description
This adds the `programs.qutebrowser.greasemonkey` option, a list of packages that represent greasemonkey userscripts.

### Checklist

- [X] Change is backwards compatible.

- [X] Code formatted with `./format`.

- [X] Code tested through `nix-shell --pure tests -A run.all`.

- [X] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [X] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

2023-03-16 20:04 UTC, somasis commented
This looks mostly okay, but there's a few things I wonder about:

- Currently there's no handling of qutebrowser's `@require` downloading; this could cause errors on startup (and scripts to not load) if scripts in `~/.config/qutebrowser/greasemonkey` have any `@require` statements not satisfied by the script derivative itself, since the generated `greasemonkey` directory is read-only (because it's in the nix store) and thus qutebrowser can't download anything itself. There ought to be a way to do the `require` downloading declaratively (or at least, make the `requires` directory writable).
- Maybe `programs.qutebrowser.greasemonkey` should also be able to take paths and strings in addition to derivatives? Otherwise for scripts one is referring to within the configuration path, you have to do something like `pkgs.writeTextFile "script.js" ./script.js`. I'm not really sure if there's precedent for doing this in this option but it was just something that occurred to me while configuring this on my system.

2023-03-21 01:19 UTC, somasis commented
> This looks mostly okay, but there's a few things I wonder about:
> 
> * Currently there's no handling of qutebrowser's `@require` downloading; this could cause errors on startup (and scripts to not load) if scripts in `~/.config/qutebrowser/greasemonkey` have any `@require` statements not satisfied by the script derivative itself, since the generated `greasemonkey` directory is read-only (because it's in the nix store) and thus qutebrowser can't download anything itself. There ought to be a way to do the `require` downloading declaratively (or at least, make the `requires` directory writable).

Actually, I wasn't entirely correct; qutebrowser downloads the `@require`d scripts to its data directory (`~/.local/share/qutebrowser/greasemonkey/requires`), so it's probably not as big a problem I made it out to be.

2023-07-07 15:51 UTC, somasis commented
Anything still preventing this from being merged?

2023-07-07 17:46 UTC, sumnerevans requested changes

2023-07-07 17:46 UTC, sumnerevans commented on modules/programs/qutebrowser.nix
> +
why did this get moved? If for no reason, then please undo this change.

2023-07-07 17:46 UTC, sumnerevans commented on tests/modules/programs/qutebrowser/default.nix
> +  qutebrowser-greasemonkey = ./greasemonkey.nix;
these lines really should be sorted, but I guess it was already unsorted, so this is fine

2023-07-16 00:58 UTC, sisyphushappy commented
Opened #4239 to finalize this PR.

2023-10-18 20:59 UTC, rycee commented
Resolved by merging the PR mentioned above.

2023-10-18 20:59 UTC, closed without merging