yambar: add module
nix-community/home-manager pull request #3353
Opened 2022-10-25 16:24 UTC by carpinchomug

### Description

This adds a module for [Yamber](https://codeberg.org/dnkl/yambar), a modular status panel for X11 and Wayland.

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all`.

- [x] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [x] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [x] Added myself and the module files to `.github/CODEOWNERS`.

2022-11-21 21:18 UTC, h7x4 requested changes

2022-11-21 21:18 UTC, h7x4 commented on modules/programs/yambar.nix
> +      };
```suggestion
      package = mkPackageOption pkgs "yambar" { };
```

2023-02-07 23:44 UTC, m-bdf commented
When using the [map particle](https://www.mankier.com/5/yambar-particles#Map), yambar evaluates the conditions in the order they appear in the config file.
However, the YAML generator always outputs Nix attribute sets alphabetically, so using a map in this modules's `settings` option won't work as expected (same as #2519, potential future solution in #3481).

For example, the Nix value
```nix
{
  river.content = {
    map.conditions = {
      "focused" = …;
      "occupied" = …;
      "id < 10" = …;
    };
  };
}
```
will be rendered to YAML as
```yaml
river:
  content:
    map:
      conditions:
        focused: …
        id < 10: …
        occupied: …
```
(notice the wrong order).

---

FWIW, here is a workaround for this example, using `~(…)` to negate each condition:
```nix
{
  river.content = {
    map.conditions = {
      "focused" = …;
      "~(focused)" = {
        map.conditions = {
          "occupied" = …;
          "~(occupied)" = {
            map.conditions = {
              "id < 10" = …;"
            };
          };
        };
      };
    };
  };
}
```
rendered as
```yaml
river:
  content:
    map:
      conditions:
        focused: …
        ~(focused):
          map:
            conditions:
              occupied: …
              ~(occupied):
                map:
                  conditions:
                    id < 10: …
```
(which is verbose and ugly, but will be evaluated as intended).

Also, here is a Nix helper function to generate the boilerplate from an ordered list of condition/particle pairs:
```nix
mkOrderedMapParticle =
  foldl' (res: { condition, particle }: {
    map.conditions = {
      "${condition}" = particle;
    } // optionalAttrs (res != null) {
      "~(${condition})" = res;
    };
  });
```
used like this:
```nix
{
  river.content = mkOrderedMapParticle null [
    { condition = "focused"; particle = …; }
    { condition = "occupied"; particle = …; }
    { condition = "id < 10"; particle = …; }
  ];
}
```
(the first argument being an optional default particle).

2024-03-01 12:19 UTC, madsrumlenordstrom commented
> ```nix
> {
>   river.content = mkOrderedMapParticle null [
>     { condition = "focused"; particle = …; }
>     { condition = "occupied"; particle = …; }
>     { condition = "id < 10"; particle = …; }
>   ];
> }
> ```
I would be satisfied using this solution.

2024-04-17 14:12 UTC, ivan770 commented
Not sure if it's a proper scope for this PR, but would it be reasonable to add a systemd-based activation support for yambar?

2024-04-17 16:15 UTC, madsrumlenordstrom commented
> Not sure if it's a proper scope for this PR, but would it be reasonable to add a systemd-based activation support for yambar?

I think it would be a good idea to add systemd activation. I actually use this in my personal home-manager configuration. You can check it out [here](https://github.com/madsrumlenordstrom/nixos-config/blob/dd981dcb9e55c5e8b6e2bccff0485304573314b9/modules/home-manager/yambar.nix). I am no expert in systemd services so maybe there is a better way to do it.

2024-05-10 21:16 UTC, rycee commented on modules/programs/yambar.nix
> +          for options.
Can switch to Markdown

```suggestion
          Configuration written to
          {file}`$XDG_CONFIG_HOME/yambar/config.yml`.
          See {manpage}`yambar(5)` for options.
```

2024-05-10 21:49 UTC, merged

2024-05-10 21:54 UTC, rycee commented
Thanks and apologies for the delay. I've merged this to master now.

I agree that this module should define a systemd service. Well worth a future PR for any interested person.

About the particles, it does seem like an odd way to use YAML and I think the proposed workaround doesn't look too bad. So probably also worth a future PR.