zimfw: add module
nix-community/home-manager pull request #3534
Opened 2022-12-28 15:46 UTC by joedevivo

[zimfw](https://zimfw.sh) is "The Zsh configuration framework with blazing speed and modular extensions."

This module allows it to be configured via home-manager.

### Description

Added [zimfw](https://zimfw.sh).

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all`.

- [x] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [x] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [x] Added myself and the module files to `.github/CODEOWNERS`.

2023-01-03 14:38 UTC, sumnerevans requested changes
let's git zim packaged in nixpkgs before adding the module to hm

2023-01-03 14:38 UTC, sumnerevans commented on modules/programs/zimfw.nix
> +  zimPkg = pkgs.stdenv.mkDerivation rec {
Is there a PR to add it to nixpkgs? I think that we would want that done so that we don't maintain any package derivations in home-manager.

2023-01-03 14:38 UTC, sumnerevans commented on modules/programs/zimfw.nix
> +        fi
checking that this file exists should probably just be part of the test phase of the package

2023-01-05 13:09 UTC, joedevivo commented
I've opened nixos/nixpkgs#208919, and I'll wait for that to get merged before updating this.

2023-01-18 13:47 UTC, joedevivo commented
@sumnerevans `zimfw` has been added to nixpkgs, and this is ready for review

2023-01-31 12:51 UTC, joedevivo commented
I don't think this is ever going to get anyone's attention. I'll have to assume it's an issue with notifications or something, so I'm going to close this PR and open a new one with the same content.

2023-01-31 12:51 UTC, closed without merging