easyeffects: add package option
nix-community/home-manager pull request #3568
Opened 2023-01-05 15:20 UTC by pltanton

### Description

Add package option to `service.easyeffects'.

There is some bugs in package, that you may want to fix by overriding. F.e. https://github.com/NixOS/nixpkgs/issues/189481

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [ ] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

2023-01-05 17:16 UTC, sumnerevans requested changes

2023-01-05 17:16 UTC, sumnerevans commented on modules/services/easyeffects.nix
>          ExecStop = "${pkgs.easyeffects}/bin/easyeffects --quit";
```suggestion
        ExecStop = "${cfg.package}/bin/easyeffects --quit";
```

2023-01-06 01:01 UTC, pltanton commented on modules/services/easyeffects.nix
>          ExecStop = "${pkgs.easyeffects}/bin/easyeffects --quit";
Missed it. Fixed.

2023-01-06 04:39 UTC, sumnerevans approved these changes

2023-01-06 04:49 UTC, merged

2023-01-06 17:09 UTC, felschr commented
Can this be backported to 22.11? Would be useful to try the new major easyeffects version on the stable NixOS channel.