himalaya: improve derivation for v0.7.0
nix-community/home-manager pull request #3664
Opened 2023-02-09 14:43 UTC by soywod

### Description

I tried to make the derivation safer and closer to the configuration file. I added missing options, added two services and added more tests. It should be ready for the last release v0.7.0.

Note: I am the author of the tool, and I feel confortable enough now with Nix to be part of maintainers in order to reduce delay between releases.

### Checklist

- [X] Change is backwards compatible.

- [X] Code formatted with `./format`.

- [X] Code tested through `nix-shell --pure tests -A run.all`.

- [X] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [X] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

cc @toastal

2023-02-09 17:27 UTC, ambroisie commented
You should make a separate commit to add yourself to the maintainers file.

2023-02-09 17:29 UTC, soywod commented
> You should make a separate commit to add yourself to the maintainers file.

Sure, I do it now!

2023-02-09 17:29 UTC, ambroisie commented
As for adding more options to the module, unless it provides more integration with the email infrastructure in home-manager, I believe it is frowned-upon to simply mirror every option into the module system, if instead a free-form type could suffice.

I have yet to take a deeper look at your changes, but just letting you know in advance :-).

2023-02-09 17:44 UTC, soywod commented
> As for adding more options to the module, unless it provides more integration with the email infrastructure in home-manager, I believe it is frowned-upon to simply mirror every option into the module system, if instead a free-form type could suffice.

Ow, I thought that explicitly writing down all options would make the module more self-documented and safer, but I also understand the fact to forward everything. Anyway I can rollback if needed, it is not a big deal.

2023-02-09 22:19 UTC, toastal commented
@rycee is this true? Would it be better to have the options _in_ Nix+home-manager when the upstream project maintainer is now doing and keeping a close eye on the home-manager project? The frowned-upon nature seemed particularly important for those not near the project and the configs break.

2023-03-24 13:15 UTC, soywod commented
Just for information, `v0.7.X` changes have been merged on [nixpkgs](https://github.com/NixOS/nixpkgs/pull/215330).

2023-04-24 10:28 UTC, j0xaf commented
I'd like to have this merged; one reason is that I need to set `folder-aliases`. The current implementation does not allow to do this, since it uses `//` as merge operation for user supplied settings and not `lib.recursiveUpdate`.

2023-04-24 11:10 UTC, ncfavier requested changes
I've only done a very superficial review, but the main concern is that this adds [too many options](https://nix-community.github.io/home-manager/index.html#sec-guidelines-valuable-options). Please see [RFC 42](https://github.com/NixOS/rfcs/blob/master/rfcs/0042-config-option.md) and add freeform types as needed instead.

2023-04-24 11:10 UTC, ncfavier commented on tests/modules/programs/himalaya/default.nix
> -{ himalaya = ./himalaya.nix; }
`himalaya.nix` is now unused

2023-04-24 11:10 UTC, ncfavier commented on modules/programs/himalaya.nix
> +      '';
That's not a `literalExpression`, that's a string.

2023-04-24 11:10 UTC, ncfavier commented on modules/programs/himalaya.nix
> +      '';
`literalExpression` doesn't make sense in option descriptions.

2023-04-24 11:10 UTC, ncfavier commented on modules/programs/himalaya.nix
> +      '';
```suggestion
      example = [ "mbsync -a" ];
```

2023-04-24 15:31 UTC, soywod commented
@ncfavier I just push your changes. I removed all the options and used the `freeformType` instead.

@j0xaf I also replaced `//` by `lib.recursiveUpdate` and add a test to check that `folder-aliases` are correctly overridden.

The PR is ready for another review.

2023-04-25 10:15 UTC, ncfavier approved these changes

2023-04-25 10:15 UTC, ncfavier commented on modules/programs/himalaya.nix
> +      package = lib.mkOption {
Could use `mkPackageOption pkgs "himalaya" { }`.

2023-05-04 10:28 UTC, merged

2023-05-04 23:14 UTC, soywod commented on tests/modules/programs/himalaya/basic.nix
> +      himalaya.sender = "deprecated";
I will modify this for the next release