xfconf: fix dbus may not be started in NixOS.
nix-community/home-manager pull request #3707
Opened 2023-02-26 15:02 UTC by gou4shi1

### Description

fix https://github.com/nix-community/home-manager/pull/3378#issuecomment-1368015573

### Checklist

- [x] Change is backwards compatible.

- [ ] Code formatted with `./format`.

- [ ] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [ ] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

2023-02-26 15:35 UTC, ncfavier requested changes
This seems to be taken verbatim from the dconf module; some deduplication would be nice, though I don't have any good ideas that don't force a dependency on `dbus`.

Please squash the commits into one and name it according to the [contribution guidelines](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style).

2023-02-26 15:35 UTC, ncfavier commented on modules/misc/xfconf.nix
> +          export DCONF_DBUS_RUN_SESSION=""
```suggestion
          export XFCONF_DBUS_RUN_SESSION=""
```

2023-02-26 15:36 UTC, ncfavier commented
Oh, and please target `master`. We'll backport later if needed.

2023-02-26 16:10 UTC, gou4shi1 commented
@ncfavier Thanks for your review :)

2023-02-26 16:24 UTC, ncfavier approved these changes

2023-02-28 15:27 UTC, gou4shi1 commented
Would it be merged?

2023-02-28 15:29 UTC, ncfavier commented
I'm giving the other maintainers some time to review this; will merge in a couple days if no one objects.

2023-03-05 08:47 UTC, merged