wofi: add module
nix-community/home-manager pull request #3786
Opened 2023-03-18 21:06 UTC by christoph-heiss

### Description

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all`.

- [x] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [x] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [x] Added myself and the module files to `.github/CODEOWNERS`.

2023-04-14 16:46 UTC, christoph-heiss commented
Updated this a bit by
- Removing myself from `modules/lib/maintainers.nix`, as I'm listed in the nixpkgs' list now
- Simplified config generation a lot

Happy to change things as needed to get this merged.

2023-04-18 15:01 UTC, sumnerevans requested changes

2023-04-18 20:34 UTC, christoph-heiss commented
Thanks for the review @sumnerevans, I've changed all the things according to your suggestions!

2023-04-19 14:13 UTC, sumnerevans requested changes

2023-04-19 14:13 UTC, sumnerevans commented on .github/CODEOWNERS
> +
Oh, just realized this is a program not a service. It should go up with the programs around line 350

2023-04-19 14:13 UTC, sumnerevans commented on tests/default.nix
> +    ./modules/programs/wofi
should come after wlogout

2023-04-19 14:20 UTC, christoph-heiss commented
Thanks again, fixed both these things!

2023-04-19 19:17 UTC, sumnerevans approved these changes

2023-04-20 06:11 UTC, merged