darkman: add module
nix-community/home-manager pull request #3919
Opened 2023-04-25 16:33 UTC by xlambein

### Description

This adds a service module for the `darkman` utility.  The module starts a `darkman` service, and allows you to configure your location and other `darkman` settings.  It also offers the possibility to set scripts that are triggered when entering dark or light mode.

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all`.

- [x] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [x] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [x] Added myself and the module files to `.github/CODEOWNERS`.

2023-06-20 08:12 UTC, vlaci commented
I have copy-pasted this module to my personal configuration, and it works like a charm.

2023-06-20 08:58 UTC, ncfavier commented on modules/services/darkman.nix
> +            ${pkgs.dconf}/bin/dconf write \
```suggestion
            ''${pkgs.dconf}/bin/dconf write \
```

2023-06-20 08:58 UTC, ncfavier commented on modules/services/darkman.nix
> +    };
```suggestion
    package = mkPackageOption pkgs "darkman" { };
```

2023-06-20 08:58 UTC, ncfavier commented on modules/services/darkman.nix
> +        Environment = "PATH=${makeBinPath [ pkgs.bash ]}";
Shouldn't scripts have shebangs pointing to the Nix store? Why is bash singled out? Is there a use case for `#!/usr/bin/env bash` scripts to work out of the box?

2023-06-21 06:49 UTC, xlambein commented
Thanks for the review @ncfavier !

2023-06-22 21:34 UTC, rycee commented on modules/services/darkman.nix
> +      };
I guess the service should be restarted if the configuration file changes? If so, then need to add something like

```suggestion
        X-Restart-Triggers =
          [ "${config.xdg.configFile."darkman/config.yaml".source}" ];
      };
```

to make sure the service file changes when the configuration changes.

Not sure about the dark and light mode scrips. I guess changing those will not require a service restart?

2023-06-22 21:37 UTC, rycee commented on modules/services/darkman.nix
> +        ExecStart = "${cfg.package}/bin/darkman run";
Not particularly important, but perhaps could try

```suggestion
        ExecStart = "${getExe cfg.package} run";
```

2023-06-22 21:39 UTC, rycee commented
Thanks, looks good! Only added one comment of any importance, supporting service restart on reconfiguration would be nice.

2023-06-25 13:14 UTC, xlambein commented
Thanks @rycee! I incorporated your comments into the module.

2023-07-01 00:04 UTC, sumnerevans requested changes

2023-07-01 00:04 UTC, sumnerevans commented on modules/services/darkman.nix
> +        (generateScripts "light-mode.d" cfg.lightModeScripts))
These scripts should be under `darkman/{dark,light}-mode.d`.

```suggestion
      (mkIf (cfg.darkModeScripts != { })
        (generateScripts "darkman/dark-mode.d" cfg.darkModeScripts))
      (mkIf (cfg.lightModeScripts != { })
        (generateScripts "darkman/light-mode.d" cfg.lightModeScripts))
```

2023-10-15 10:35 UTC, xlambein commented
I believe I've addressed everything in this PR. There's one remaining change requested, which as I've commented is not correct. Can someone help me finalize this?

2023-10-17 07:54 UTC, merged

2023-10-17 09:54 UTC, xlambein commented
Thank you @rycee !