cava: init program with settings configuration
nix-community/home-manager pull request #4100
Opened 2023-06-16 19:41 UTC by bddvlpr

### Description

Added cava program definition that allows automatic generation of the INI configuration file (`.config/cava/config`) with a given attribute set. Camel case attributes will be converted into snake case to abide the configuration properties.

### Checklist

- [X] Change is backwards compatible.

- [X] Code formatted with `./format`.

- [X] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.

- [X] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [X] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [X] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

2023-06-16 23:32 UTC, sumnerevans requested changes

2023-06-16 23:32 UTC, sumnerevans commented on modules/programs/cava.nix
> +    };
```suggestion
    package = mkPackageOption pkgs "cava" { };
```

2023-06-16 23:33 UTC, sumnerevans commented
Also needs a news entry

2023-06-17 16:34 UTC, bddvlpr commented
My bad, I just noticed the typo, will fix as soon as I’m home again.

2023-07-24 16:30 UTC, bddvlpr commented
@sumnerevans Would you mind re-reviewing the changes I've made?

2023-10-23 09:45 UTC, bddvlpr commented
@sumnerevans Mentioning again since it's now marked stale.

2023-10-24 06:33 UTC, merged

2023-10-24 06:34 UTC, rycee commented
Thanks! I've merged this to master now. Note, I removed the camel case to snake case conversion since we typically avoid doing such transformations when doing RFC42 style settings options.