Jetbrains remote dev
nix-community/home-manager pull request #4269
Opened 2023-07-23 20:44 UTC by GenericNerdyUsername

### Description

This adds a module that allows you to select the IDEs accessible using gateway and a ssh connection

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [x] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

2023-07-25 04:12 UTC, sumnerevans commented on modules/programs/jb-remote.nix
> +    ides = mkOption {
should we be installing these IDEs into `home.packages` as well?

2023-08-02 14:32 UTC, sumnerevans requested changes

2023-08-02 14:32 UTC, sumnerevans commented on modules/programs/jb-remote.nix
> +  options.programs.jb-remote = {
I don't think we have any abbreviations elsewhere, so we should probably say `jetbrains-remote` or similar instead of `jb-remote` .

2023-11-06 16:55 UTC, sumnerevans approved these changes

2024-02-05 23:29 UTC, merged

2024-02-05 23:29 UTC, rycee commented
Thanks! Merged to master now. Note, I added an `enable` option that needs to be enabled for the module to take effect.