git: replace gitToInit with lib function
nix-community/home-manager pull request #4357
Opened 2023-08-17 18:22 UTC by VwCSXg

### Description
Remove the function gitToInit and underlying functions in favor of using the function lib.generators.toGitINI from nixpkgs. The latter parses the configuration contents, particulary strings, with less escaping, which is why the test configurations had to be ammended accordingly.
closes #4354

### Checklist

- [x ] Change is backwards compatible.

- [ x] Code formatted with `./format`.

- [ x] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.

- [x ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [ x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

#### Maintainer CC
@rycee

2023-08-17 19:35 UTC, ncfavier requested changes
The quote removal seems like a no-go: I have config values with `#` that definitely should be quoted. Why does the nixpkgs generator remove quotes?

2023-08-17 19:35 UTC, ncfavier commented on tests/modules/programs/git/git-expected.conf
> +	path = /nix/store/y0c46dscy39gfhbd59b2vjjiysry5vpp-hm_gitconfigwork
!

2023-08-17 19:43 UTC, ncfavier commented
Proper quoting was added in HM after the extraction: https://github.com/nix-community/home-manager/pull/1209

This will have to be upstreamed as well before this PR can proceed.

2023-08-19 14:26 UTC, VwCSXg commented
> Proper quoting was added in HM after the extraction: #1209
Thanks for pointing that out, I missed that.

> This will have to be upstreamed as well before this PR can proceed.
You're right, I'll try that.

2023-09-18 22:16 UTC, merged

2023-09-18 22:16 UTC, rycee commented
Thanks! Looks good now :-)