neovim: Add missing newlines to init.lua
nix-community/home-manager pull request #4390
Opened 2023-08-30 06:34 UTC by Talljoe

### Description

When generating `init.lua` the Lua config would be placed immediately
after the nvim config without a new line.

```
vim.cmd [[source /nix/store/cs3al9x1ml5ds3n6n433wcdxp89awac4-nvim-init-home-manager.vim]]--first line of Lua config
```

This change places a newline after each config portion.

```
vim.cmd [[source /nix/store/cs3al9x1ml5ds3n6n433wcdxp89awac4-nvim-init-home-manager.vim]]
--first line of Lua config
```

### Checklist

- [X] Change is backwards compatible.

- [X] Code formatted with `./format`.

- [X] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.

- [X] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [X] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

#### Maintainer CC

2023-11-05 21:12 UTC, teto approved these changes
cant merge because of CI, try a rebase maybe

2023-11-15 23:53 UTC, Talljoe commented
I will try to fixup this PR this weekend

2024-02-14 15:19 UTC, sumnerevans requested changes

2024-02-14 15:19 UTC, sumnerevans commented on modules/programs/neovim.nix
> +      vimRcContent = lib.optionalString (neovimConfig != "") pkgs.writeText
It seems like this is what it used to be...

```suggestion
      vimRcContent = lib.optionalString (neovimConfig.neovimRcContent != "") pkgs.writeText
```

2026-08-26 23:18 UTC, teto commented
I beleive it's fixed

2026-08-26 23:18 UTC, closed without merging