openstackclient: add module
nix-community/home-manager pull request #4530
Opened 2023-10-04 18:49 UTC by tensor5

### Description

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.

- [x] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [x] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

#### Maintainer CC

2023-11-03 21:39 UTC, sumnerevans requested changes

2023-11-03 21:39 UTC, sumnerevans commented on modules/programs/openstackclient.nix
> +    };
```suggestion
    package = lib.mkPackageOption pkgs "openstackclient";
```

2023-11-03 21:39 UTC, sumnerevans commented on modules/programs/openstackclient.nix
> +    home.file."${config.home.homeDirectory}/.config/openstack/clouds.yaml".source =
```suggestion
    xdg.configFile."openstack/clouds.yaml".source =
```

2023-11-03 21:39 UTC, sumnerevans commented on modules/programs/openstackclient.nix
> +    home.file."${config.home.homeDirectory}/.config/openstack/clouds-public.yaml".source =
```suggestion
    xdg.configFile."openstack/clouds-public.yaml".source =
```

2023-11-06 16:49 UTC, sumnerevans commented on modules/programs/openstackclient.nix
> +        Configuration written to {file}`~/.config/openstack/clouds.yaml`.
```suggestion
        Configuration written to {file}`$XDG_CONFIG_HOME/openstack/clouds.yaml`.
```

2023-11-06 16:50 UTC, sumnerevans commented on modules/programs/openstackclient.nix
> +        };
```suggestion
        }
```

2023-11-06 16:54 UTC, sumnerevans commented
once you've made all of your changes, please also squash into a single commit

2023-11-06 18:43 UTC, sumnerevans approved these changes
lgtm

2023-11-15 08:41 UTC, tensor5 commented
Can someone approve the workflow, please?

2023-11-15 22:25 UTC, merged