k9s: add aliases, plugins, views
nix-community/home-manager pull request #4627
Opened 2023-11-02 07:11 UTC by katexochen

### Description

Adding the remaining config files for k9s. Documented at https://k9scli.io/

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.

- [x] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

#### Maintainer CC

@liyangau

2023-11-03 15:50 UTC, sumnerevans requested changes
just nits, otherwise looks good

2023-11-03 15:50 UTC, sumnerevans commented on modules/programs/k9s.nix
> +        aliases written to
```suggestion
        Aliases written to
```

2023-11-03 15:50 UTC, sumnerevans commented on modules/programs/k9s.nix
> +        plugins written to
```suggestion
        Plugins written to
```

2023-11-03 15:50 UTC, sumnerevans commented on modules/programs/k9s.nix
> +        resource column views written to
```suggestion
        Resource column views written to
```

2023-11-11 00:41 UTC, rycee commented
Thanks for the contribution! I rebased it to master in 691cbcc03af6ad1b5384c0e0e0b5f2298f58c5ce 🙂

2023-11-11 00:41 UTC, closed without merging