targets/darwin: allow configuring application linking
nix-community/home-manager pull request #4809
Opened 2023-12-24 23:31 UTC by moni-dz

### Description

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

#### Maintainer CC

@midchildan

2024-04-01 18:29 UTC, sumnerevans requested changes

2024-04-01 18:29 UTC, sumnerevans commented on modules/targets/darwin/linkapps.nix
> +    };
```suggestion
    enable = mkEnableOption "linking macOS applications to the user environment" // {
      default = true;
    };
```

2024-04-01 18:29 UTC, sumnerevans commented on modules/targets/darwin/linkapps.nix
> +      defaultText = "Applications/Home Manager Apps";
I don't think this is necessary anymore.

```suggestion
```

2024-04-01 18:29 UTC, sumnerevans commented on modules/targets/darwin/linkapps.nix
> +      type = types.str;
```suggestion
      type = types.path;
```

2025-02-22 22:35 UTC, khaneliman commented on modules/targets/darwin/linkapps.nix
> +      type = types.str;
This is a string that gets injected into the `home.file` below, not an actual full path.

2025-02-22 22:36 UTC, khaneliman approved these changes
Allows greater flexibility and verified it works locally, thanks

2025-02-22 23:00 UTC, merged