jq: add module
nix-community/home-manager pull request #489
Opened 2018-12-09 15:05 UTC by liff

2018-12-10 04:01 UTC, kalbasit approved these changes

2018-12-11 23:53 UTC, rycee requested changes
Thanks for the contribution! I added a few minor comments. Once fixed I'd be happy to merge :+1:

2018-12-11 23:53 UTC, rycee commented on modules/programs/jq.nix
> +    example = "1;31";
I think you could change this to
```nix
  colorType = mkOption {
    type = types.str;
    visible = false;
  };
```
to suppress the individual options from showing up in the documentation. The repetitiveness is not very useful, I think the example suffices to show the available color options.

2018-12-11 23:53 UTC, rycee commented on modules/programs/jq.nix
> +
If you want a paragraph break then for technical reasons you have to put `</para><para>` instead of a blank line.

2018-12-11 23:53 UTC, rycee commented on modules/programs/jq.nix
> +        example = {
You can change this to
```nix
        example = literalExample ''
          {
            null    = "1;30";
            false   = "0;31";
            true    = "0;32";
            numbers = "0;36";
            strings = "0;33";
            arrays  = "1;35";
            objects = "1;37";
          }
        '';
```
for prettier formatting in the documentation.

2018-12-11 23:53 UTC, rycee commented on modules/programs/jq.nix
> +          See <link xlink:href="https://stedolan.github.io/jq/manual/#Colors"/>
Should end in a period.

2018-12-11 23:53 UTC, rycee commented on modules/programs/jq.nix
> +      colors = mkOption {
Generally I prefer to have blank lines between options to help spot them easier.

2018-12-11 23:53 UTC, rycee commented on modules/programs/jq.nix
> +  cfg = config.programs.jq;
Can add an empty line between the `let` and the `cfg = ...` 🙂

2018-12-12 21:05 UTC, rycee commented
Awesome! I squashed and rebased to master in dc72aa230596c5e10f4bfaf519392999dfd343cd. Thanks for the contribution!

2018-12-12 21:06 UTC, closed without merging