Add possibility to import systemd services from packages
nix-community/home-manager pull request #4990
Opened 2024-02-02 13:13 UTC by khlopkov

### Description

Packages installed through `home.packages` can contain systemd services. Those services are stored in `~/.nix-profile/share/systemd/user/` but they do not exist in `~/.config/systemd/user/`. That's why currently it is not possible to enable those services without linking them manually (or copying/creating new ones). I described in the following issue: https://github.com/nix-community/home-manager/issues/4972

This PR intents to add a new option `systemd.user.servicesOfPackages` that supposed to enable services declared in packages provided into the option.

Also that causing a bug (https://github.com/nix-community/home-manager/issues/4922) on non-NixOS environments with `xdg.portal.extraPortals` options, because services from `extraPortals` packages can not be found by `xdg-desktop-portal.service`. This PR fixes this bug as well by using the new `systemd.user.servicesOfPackages` option. It seems that there are other similar issues listed in the thread with other options, this PR does not fix them, but I hope this PR will help to fix them easier.

### Checklist

- [ ] Change is backwards compatible.

- [ ] Code formatted with `./format`.

- [ ] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [ ] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

#### Maintainer CC

2024-05-06 12:53 UTC, Nemo157 commented
AFAIK linking these services in isn't necessary, the combined `share/systemd/user` directory is in the search-path already (check `systemd-path systemd-search-user-unit`). The issue is more that there needs to be some way to _enable_ units defined in the packages (and not just services, sockets etc. too) by adding them to the generated `.wants` directories.

2024-05-06 16:22 UTC, chaorace commented
I just so happen to be a non-NixOS Linux user who is also affected by the issue with the extraPortals option, so I checked my own paths via `systemd-path` and confirmed that the nix-profile paths do already exist there.

With that being said, I think it would be better to properly process the [Install] section of the service unit file rather than do the linking ourselves. It looks like HM has avoided using `systemctl enable` in the past, but perhaps this is a situation where that would be warranted?

In any case, one change I'd like to see with the currently proposed configuration setup is to provide more granularity in service selection.

I seem to recall that some packages provide multiple versions of the same service where only one is intended to be used at a given time. To better handle cases like these, there should be some optional mechanism to only install specifically named services from the specified package.

2025-09-30 13:48 UTC, AntonFriberg commented
Hi! I am also running non-nixos (Ubuntu 24) and was very confused about why I was not getting xdg-desktop-portal to start or even be listed. It would be very nice if we could get some more attention on this and hopefully have a solution for non-nixOS users like myself.

2025-12-07 19:39 UTC, DerRockWolf commented
> AFAIK linking these services in isn't necessary, the combined `share/systemd/user` directory is in the search-path already (check `systemd-path systemd-search-user-unit`). 

Can someone verify this on a different system (I'm on Ubuntu 24.04).

There `systemd-path systemd-search-user-unit` does indeed contain `$HOME/.nix-profile/share/systemd/user` but `systemctl --user show -p UnitPath` does not and units that are not linked to `~/.config/systemd/user` cannot be found by systemd!

> The issue is more that there needs to be some way to _enable_ units defined in the packages (and not just services, sockets etc. too) by adding them to the generated `.wants` directories.

For this I would suggest to replicate how NixOS handles it: `systemd.*.<name>.wantedBy` ([implementation](https://github.com/NixOS/nixpkgs/blob/d9bc5c7dceb30d8d6fafa10aeb6aa8a48c218454/nixos/lib/systemd-lib.nix#L501-L511))

Until this is properly implemented one can just do:
```nix
xdg.configFile = {
  "systemd/user/default.target.wants/<name>.service".source = "${pkgs.<name>}/share/systemd/user/<name>.service";
};
```

2025-12-07 20:31 UTC, DerRockWolf requested changes
Some few things I found 🙂

Would be great if we could get this merged soon.

2025-12-07 20:31 UTC, DerRockWolf commented on modules/systemd.nix
> +      isService = (path: type: (builtins.match ".service$" path) == null);
This currently only includes files that aren't matching (`== null`) 😅 

I would do it like this (and also include `.target` files):


```suggestion
      isService = (path: type: lib.hasSuffix ".service" path || lib.hasSuffix ".target" path);
```

2025-12-07 20:31 UTC, DerRockWolf commented on modules/systemd.nix
> +      servicesOfPackages = mkOption {
As a similar option already exists for NixOS I would suggest to call it similarly.
```suggestion
      packages = mkOption {
```

2025-12-07 20:31 UTC, DerRockWolf commented on modules/systemd.nix
> +    xdg.configFile = mkMerge ([
As mentioned in https://github.com/nix-community/home-manager/issues/4972#issuecomment-3036799318 it would be "more" correct to use `xdg.dataFile`

2025-12-07 22:01 UTC, Nemo157 commented
> There `systemd-path systemd-search-user-unit` does indeed contain `$HOME/.nix-profile/share/systemd/user` but `systemctl --user show -p UnitPath` does not and units that are not linked to `~/.config/systemd/user` cannot be found by systemd!

Mine does

```console
> systemctl --user show -p UnitPath | rg --only-matching "$HOME/.nix-profile/share/systemd/user"
/home/nemo157/.nix-profile/share/systemd/user
```

But that's not where the services seem to get installed, instead they're in `/etc/profiles/per-user/$USER/share/systemd/user` (maybe because I use home-manager via the nixos module).

For the [`u2f-touch-detector` module](https://github.com/Nemo157/u2f-touch-detector/blob/main/module.nix) I don't explicitly install the service anywhere, but I have the package in `home.packages` and that causes the service to end up in `/etc/profiles/per-user/nemo157/share/systemd/user/u2f-touch-detector.service`, then the module just adds the correct `.wants` symlink to make systemd activate it.

2025-12-08 20:24 UTC, DerRockWolf commented
@Nemo157 yes, because you are on NixOS. There everything works as expected because `~/.nix-profile/share/systemd/user` is already included in the unit search path.
On non NixOS systems where you just use home-manager `~/.nix-profile/share/systemd/user` is not included in the unit search path, because the distribution obviously doesn't know that there might be units located there.

2025-12-09 14:19 UTC, Nemo157 commented
Maybe on non-NixOS it should automatically replicate the same kind of setup: symlink all units from `home.packages` into `xdg.dataHome`.

2025-12-16 02:46 UTC, teto commented
can you address and rebase comments please ?

2026-01-11 03:10 UTC, Invizory commented on modules/systemd.nix
> +      servicesOfPackages = mkOption {
Moreover, we already have a similar option `dbus.packages`, so this would be better for consistency.

2026-01-11 07:48 UTC, Invizory commented
I have created an alternative implementation in #8540, focused solely on systemd user units without messing with `xdg.portal`, which I believe could be discussed and resolved in #8541.

2026-07-29 06:04 UTC, khaneliman commented
Superseded by #8540; remaining portal wiring continues in #8541.

2026-07-29 06:04 UTC, closed without merging