spotify-player: add module
nix-community/home-manager pull request #5178
Opened 2024-03-24 21:40 UTC by diniamo

### Description

Adds a module for `spotify-player` with the fields `enable`, `package`, `settings`, `themes`, `keymaps`.

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.

- [x] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [ ] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [x] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

2024-03-24 21:44 UTC, diniamo commented
Do the commits really have to be renamed? Can't the pull request be merged while squashing?

If so, what to and how do I rename them?

2024-03-25 16:14 UTC, diniamo commented
Should be good now, I think

2024-03-25 16:54 UTC, sumnerevans requested changes

2024-03-25 16:54 UTC, sumnerevans commented on modules/programs/spotify-player.nix
> +    };
```suggestion
    package = mkPackageOption pkgs "spotify-player" { };
```

2024-03-25 16:54 UTC, sumnerevans commented on modules/programs/spotify-player.nix
> +      type = types.listOf types.attrs;
not sure if this works, but I think it's better than just `types.attrs` if it works

```suggestion
      type = types.listOf tomlFormat.type;
```

2024-03-25 16:54 UTC, sumnerevans commented on modules/programs/spotify-player.nix
> +      type = types.listOf types.attrs;
```suggestion
      type = types.listOf tomlFormat.type;
```

2024-03-25 16:54 UTC, sumnerevans commented on tests/modules/programs/spotify-player/settings.nix
> +  test.stubs.yazi = { };
I assume this was a copy-paste error.

```suggestion
  test.stubs.spotify-player = { };
```

2024-03-25 18:35 UTC, diniamo commented
Suggestions, implemented, tests still run.

That last one is something else though.

2024-03-25 18:45 UTC, sumnerevans requested changes
Try rebasing on `master`? The tests are passing there.

Also, please squash this down to a single commit.

2024-03-25 20:10 UTC, diniamo commented
If you check the error, then it's saying it can't find me in the maintainers list. I have no idea why though.

2024-03-26 03:43 UTC, sumnerevans requested changes
Ah, the issue is that `lib.maintainers` is the list of Nixpkgs maintainers, not the Home Manager maintainers.

2024-03-26 03:43 UTC, sumnerevans commented on modules/programs/spotify-player.nix
> +  meta.maintainers = with lib.maintainers; [ diniamo ];
```suggestion
  meta.maintainers = with lib.hm.maintainers; [ diniamo ];
```

2024-03-26 06:28 UTC, diniamo commented
All done!

2024-03-26 20:06 UTC, sumnerevans approved these changes

2024-04-16 20:38 UTC, diniamo commented
:sob:

2024-04-19 10:39 UTC, merged

2024-04-19 10:39 UTC, rycee commented
Thanks! Merged to master now 🙂

2024-09-29 01:51 UTC, repparw commented
Hi! i'm pretty new to nix and hm so I don't know what the proper way to raise this question is so I'm dropping it here, sorry!
Is there a proposal for adding actions to the module? It's a special type of keymap added to spotify-player in 0.19.1

`[[keymaps]]
command = "LyricPage"
key_sequence = "g l"

[[actions]]
action = "CopyLink"
key_sequence = "y"
target = "PlayingTrack"
`

it probably would be very similar to keymap adding an optional target (and it would have to be merged to the same keymap.toml file)

2024-09-29 07:29 UTC, diniamo commented
How do actions differ from keymaps? I don't get it exactly.

2024-09-29 07:33 UTC, diniamo commented
Although it seems like we will be adding an `actions` option to avoid breaking changes.

2024-09-29 12:42 UTC, repparw commented
apart from having a different heading in the file I think not much. I mean,
the commands are different, but I don't think the module checks for
validity on those?

On Sun, 29 Sept 2024, 04:33 diniamo, ***@***.***> wrote:

> Although it seems like we will be adding an actions option to avoid
> breaking changes.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/nix-community/home-manager/pull/5178#issuecomment-2381218848>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AK6S7SVAP3JXQAOXP7FMOMLZY6UMRAVCNFSM6AAAAABPBEEVKCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGOBRGIYTQOBUHA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>