generators.toKDL: support repeated nodes, break JiK compat
nix-community/home-manager pull request #5272
Opened 2024-04-15 12:49 UTC by jrobsonchase

Replaces the list attr -> KDL conversion logic with a more flexible approach, allowing for multiple nodes with the same name in a scope. This unfortunately also breaks the existing JSON-in-KDL semantics in favor of ergonomics. As far as I can tell though, zellij is the only program using it, and it doesn't accept JiK anyway.

For example, the following KDL was previously impossible to generate, since nix attrs were mapped 1:1 to KDL nodes:
```kdl
resize {
	bind "k" "Up" { Resize "Increase Up"; }
	bind "j" "Down" { Resize "Increase Down"; }
}
```

Now, this can be achieved with the nix expression:

```nix
resize.bind = [
	{ _args = ["k" "Up"]; Resize = "Increase Up"; }
	{ _args = ["j" "Down"]; Resize = "Increase Down"; }
];
```

which would previously have generated the not-very-useful:

```kdl
resize {
	bind {
		- "k" "Up" { Resize "Increase Up"; }
		- "j" "Down" { Resize "Increase Down"; }
	}
}
```

which, in turn, can now be generated via:

```nix
resize.bind."-" = [
	{ _args = ["k" "Up"]; Resize = "Increase Up"; }
	{ _args = ["j" "Down"]; Resize = "Increase Down"; }
];
```

### Description

### Checklist

- [ ] ~Change is backwards compatible.~
  It's explicitly not. I'm not sure that the previous behavior that's being broken was actually usable, so it doesn't seem worth keeping intact at the cost of ergonomics.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.

- [x] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

#### Maintainer CC

@h7x4 
@mainrs

2024-04-15 13:03 UTC, jrobsonchase commented
Whoops, should've searched a little harder. Looks like KDL improvements were in progress over in #4614 at some point, but the efforts may have stalled?

2024-07-14 13:59 UTC, mainrs commented
I'll take a look next weekend!

2024-07-26 08:19 UTC, mdrssv commented
Is there any help needed to further the effort?

2024-07-29 13:58 UTC, mainrs commented
This seems to be a sensible change. I am not too sure on how to handle the merge. Since this technically breaks existing configurations, doesn't it? As you mentioned though, previous _valid_ configurations could only have been ones that do not use the above KDL syntax (I think). It's better safe to be sorry, though.

2024-07-29 14:00 UTC, mainrs requested changes
Could you add a test that specifically tests for repeated nodes as in the examples you posted with the bind syntax?

One that generates something like this:

```kdl
resize {
	bind "k" "Up" { Resize "Increase Up"; }
	bind "j" "Down" { Resize "Increase Down"; }
}
```

2025-09-23 02:26 UTC, khaneliman commented
https://github.com/nix-community/home-manager/pull/7429 addresses already? Resolve conflicts and reopen if i'm wrong.

2025-09-23 02:26 UTC, closed without merging