sway: add preCheckConfig to customize check environment
nix-community/home-manager pull request #5315
Opened 2024-04-21 13:23 UTC by amarshall

### Description

See commit messages.

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.

- [x] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

#### Maintainer CC

@Scrumplex @alexarice @sumnerevans @oxalica

2024-04-22 13:33 UTC, teto requested changes
not worth the complexity IMO. Either users make it work in hte sandbox or they disable the check. One thing we could do if there are too many complaints is to toggle the check off by default

2024-04-22 16:38 UTC, teto commented
> Where exactly is the complexity? It’s one new option and two lines of code to use it (plus tests).

the diff is 40 lines to modify the check such that it doesn't check the final config, turning it into a potentially useless check. If you dont use it I dont see why we should carry the burden upstream.

> One argument is that, unlike pkgs, it’s not possible to use overlays for modules, which causes frustration for folks when they want extensibility (so the only way to extend is to patch, which can be cumbersome for some).

You can perfectly add options under the same namespace via imports. You can see here https://github.com/teto/home/blob/main/hm/modules/zsh.nix how I extend the zsh module for instance.

2024-06-08 08:15 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/services-xserver-xkb-extralayouts-doesnt-seem-to-be-compatible-with-sway/46128/7

2024-06-08 08:34 UTC, buhl commented
I think this is a simple and elegant solution giving user the freedom to workaround their limitations of an otherwise great sway hm module. Of cause i am not the maintainer so it's easy for me to see this as no real added complexity is this feature just some extra legroom for the users.

2024-09-15 03:23 UTC, closed without merging