eww: add terminal integration options
nix-community/home-manager pull request #5645
Opened 2024-07-19 00:30 UTC by Jeansidharta

### Description

Use eww's shell-completions command to generate completions for bash, zsh and fish.

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

#### Maintainer CC

@mainrs

2024-07-24 07:05 UTC, mainrs requested changes
It would be good to see if eww also has completions for other shells like nushell. If we're already at it.

2024-07-24 07:05 UTC, mainrs commented on modules/programs/eww.nix
> +    enableBashIntegration = mkEnableOption "Bash integration";
Can you enable these completion options by default, please?

2024-07-24 07:05 UTC, mainrs commented on modules/programs/eww.nix
> +    enableZshIntegration = mkEnableOption "Zsh integration";
Same.

2024-07-24 07:05 UTC, mainrs commented on modules/programs/eww.nix
> +    enableFishIntegration = mkEnableOption "Fish integration";
Same.

2024-07-28 10:44 UTC, Jeansidharta commented
When running `eww shell-completions --shell` on version 0.6.0 I got this message:

```
[❯] eww shell-completions --shell
error: a value is required for '--shell <SHELL>' but none was supplied
  [possible values: bash, elvish, fish, powershell, zsh]

For more information, try '--help'.
```

- elvish is not in the home-manager modules
- powershell is windows only.

So, no nushell or anything else to implement, unfortunately.

2024-07-28 10:48 UTC, Jeansidharta commented
Just enabled them by default. I didn't do this at first with a fear of breaking some users environment. But this should be fine? Probably?

2024-07-28 11:45 UTC, mainrs approved these changes
> Just enabled them by default. I didn't do this at first with a fear of breaking some users environment. But this should be fine? Probably?

Good question. I just took a look at other modules and most of them enabled them by default. I guess theoretically this will override existing completions.

LGTM. I think this is ready to be merged.

2024-07-28 21:37 UTC, merged

2024-07-28 21:37 UTC, rycee commented
Thanks! Merged to master now 🙂