sheldon: add module
nix-community/home-manager pull request #5672
Opened 2024-07-25 15:34 UTC by Kyure-A

### Description
Add module for https://github.com/rossmacarthur/sheldon

### Checklist

- [X] Change is backwards compatible.

- [X] Code formatted with `./format`.

- [X] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [X] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

#### Maintainer CC

2024-07-29 12:15 UTC, mainrs requested changes
`sheldon` also provides the `sheldon completions --shell <bash|zsh>` command that prints the completion script to stdout.

Might as well add the configuration flags to the module and add the `eval` lines to bashrc/zshrc. Take a look at the `eww` module and how that is done.

2024-07-30 11:22 UTC, Kyure-A commented on modules/programs/sheldon.nix
I thought it might be too much for me too, so I changed it to make it simpler. Thanks.

2024-07-30 11:37 UTC, Kyure-A commented
I didn't know Sheldon had a completion script function. Thank you very much! I have added it as a setting.

2024-07-30 11:59 UTC, mainrs requested changes
Once changed, the PR should be ready to be merged.

2024-07-30 11:59 UTC, mainrs commented on modules/programs/sheldon.nix
> +      default = false;
These three should be `default = true`.

2024-07-30 12:12 UTC, Kyure-A commented
I would like to add you as the maintainer of this package, if you don't mind.

2024-07-30 12:12 UTC, Kyure-A commented
@mainrs

2024-07-30 19:35 UTC, mainrs commented
> The reason I have been making minor changes is probably because there is an error in the initExtra area of the shell:
> 
> ```nix
> error:
>        … while calling the 'head' builtin
> 
>          at /nix/store/qxf6anli54ij0q1sdlnlgx9hyl658a4v-source/lib/attrsets.nix:1575:11:
> 
>          1574|         || pred here (elemAt values 1) (head values) then
>          1575|           head values
>              |           ^
>          1576|         else
> 
>        … while evaluating the attribute 'value'
> 
>          at /nix/store/qxf6anli54ij0q1sdlnlgx9hyl658a4v-source/lib/modules.nix:821:9:
> 
>           820|     in warnDeprecation opt //
>           821|       { value = addErrorContext "while evaluating the option `${showOption loc}':" value;
>              |         ^
>           822|         inherit (res.defsFinal') highestPrio;
> 
>        (stack trace truncated; use '--show-trace' to show the full trace)
> 
>        error: cannot coerce a set to a string
> ```
> 
> I don't know how to deal with this error.

I think concatStrings does not handle the case when you pass it an empty list. And if both expressions are optional, that is what you get, because `mkIf` returns an empty list if the condition is false IIRC.

You can rely on the `lib.optionalString`. This is untested:

```nix
concatStringsSep "\n" [
  optionalString (cfg.settings != { })
    ''
      eval "$(sheldon source)"
    ''
  optionalString cfg.enableFishCompletions
    ''
      if test "$TERM" != "dumb"
         eval "$(${cmd} completions --shell=fish)"
      end
    ''
]
```

2024-07-31 10:59 UTC, Kyure-A commented
I have fixed this bug. Thanks for posting the code for reference.

2024-07-31 11:00 UTC, Kyure-A commented
It will probably work fine now.

2024-12-15 06:52 UTC, Kyure-A commented
@mainrs plz review it

2024-12-30 18:17 UTC, mainrs reviewed
Rest is LGTM.

2024-12-30 18:17 UTC, mainrs commented on modules/programs/sheldon.nix
> +  sheldonCmd = "${config.home.profileDirectory}/bin/sheldon";
What exactly is the difference between this and using `${cfg.package}/bin/sheldon`?

2025-02-16 07:18 UTC, onedaxter commented
Hi @Kyure-A , @mainrs 
would really like to try out this package.
anything holding off despite just doing the merge ?
thank you

2025-02-17 03:18 UTC, Kyure-A commented
> Hi @Kyure-A , @mainrs would really like to try out this package. anything holding off despite just doing the merge ? thank you

 I completely missed @mainrs's comment. There's no particular reason.

2025-02-17 03:20 UTC, Kyure-A commented on modules/programs/sheldon.nix
> +  sheldonCmd = "${config.home.profileDirectory}/bin/sheldon";
I wrote this based on a Nix expression for a certain package, so I'm not sure about the exact difference.

2025-03-20 20:40 UTC, khaneliman commented on modules/programs/sheldon.nix
> +  sheldonCmd = "${config.home.profileDirectory}/bin/sheldon";
This doesn't seem right, we should be pointing at the configured package's binary.

2025-03-20 20:40 UTC, khaneliman commented on modules/programs/sheldon.nix
> +        eval "$(sheldon source)"
Why are we relying on `PATH` here but using the `sheldonCmd` for the completions?

2025-03-20 20:40 UTC, khaneliman commented on modules/programs/sheldon.nix
> +        if [[ $TERM != "dumb" ]]; then
What are these `$TERM != "dumb"` checks for?

2025-07-22 07:18 UTC, snaeil commented
@Kyure-A Are there any plans on continuing with your PR?

2025-07-31 19:00 UTC, elanora96 commented
Hi I forked this PR and believe I implemented the changes suggested in the reviews [in this commit](https://github.com/elanora96/home-manager/commit/a9bd52ccaa05c7b9c2fe07f39593194313381c27). Honestly I'm a bit uncertain how to best contribute this without the ability to push to @Kyure-A 's branch. I don't want to end up sniping this and creating my own PR... but if there isn't a better way... I mean I do want Sheldon to be in Home Manager...

edit: The linked commit remains the most relevant one. After it I ran `./format` (my bad!) and then resolved the merge conflicts with master

(Off-topic, I like how the Copilot PR that references this PR ends up with Copilot just removing Sheldon lol)

2025-07-31 20:09 UTC, khaneliman commented
> Hi I forked this PR and believe I implemented the changes suggested in the reviews [in this commit](https://github.com/elanora96/home-manager/commit/a9bd52ccaa05c7b9c2fe07f39593194313381c27). Honestly I'm a bit uncertain how to best contribute this without the ability to push to @Kyure-A 's branch. I don't want to end up sniping this and creating my own PR... but if there isn't a better way... I mean I do want Sheldon to be in Home Manager...
> 
> edit: The linked commit remains the most relevant one. After it I ran `./format` (my bad!) and then resolved the merge conflicts with master
> 
> (Off-topic, I like how the Copilot PR that references this PR ends up with Copilot just removing Sheldon lol)

Just create a new PR that adds `Kyure-A` as a coauthor with the changes you made.

2025-08-02 07:00 UTC, closed without merging