programs.wlr-which-key: init
nix-community/home-manager pull request #5677
Opened 2024-07-27 20:24 UTC by minijackson

### Description

wlr-which-key is a keymap manager for wlroots-based compositors, inspired by which-key.nvim.

closes #4396

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.

- [x] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [x] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

#### Maintainer CC

@mightyiam, @hervyqa any of you interested in becoming co-maintainer of this module?

2024-07-28 01:01 UTC, mightyiam commented
Sure, I can be a co-maintainer.

2024-07-28 12:07 UTC, LilleAila commented
How about doing something like this? (taken from my hm config)
```nix
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.programs.wlr-which-key;
  yamlFormat = pkgs.formats.yaml { };
in
{
  options.settings.wlr-which-key = {
    enable = lib.mkEnableOption "wlr-which-key";
    settings = lib.mkOption {
      type = yamlFormat.type;
      default = { };
      example =
        lib.literalExpression # nix
          ''
            {
              font = "JetBrainsMono Nerd Font 12";
              background = "#282828cc";
              color = "#ebdbb2";
              border = "#3c3836";
              border_width = 2;
              corner_r = 12;
              padding = 16;
              separator = " -> ";

              anchor = "center"; # One of center, left, right, top, bottom, bottom-left, top-left, etc.
              margin_right = 0; # Only relevant when not center
              margin_bottom = 0;
              margin_left = 0;
              margin_top = 0;
            }
          '';
    };
    menus = lib.mkOption {
      type = lib.types.attrsOf yamlFormat.type;
      default = { };
      example =
        lib.literalExpression # nix
          ''
            {
              default = {
                w = {
                  desc = "WiFi";
                  submenu = {
                    t = {
                      desc = "Toggle";
                      cmd = "rfkill toggle wifi";
                    };
                    c = {
                      desc = "Connect";
                      cmd = "kitty -e nmtui-connect";
                    };
                  };
                };
                l = {
                  desc = "Lock";
                  cmd = "pidof swaylock || swaylock";
                };
              };
            }
          '';
    };
  };

  config = lib.mkIf cfg.enable {
    home.packages = [ pkgs.wlr-which-key ];
    xdg.configFile = lib.attrsets.mapAttrs' (
      name: menu:
      let
        filename = if name == "default" then "config" else name;
      in
      lib.attrsets.nameValuePair "wlr-which-key/${filename}.yaml" {
        source = (yamlFormat.generate "${filename}.yaml" (cfg.settings // { inherit menu; }));
      }
    ) cfg.menus;
  };
}
```

From `wlr-which-key --help`, it says that different menus can be opened from different config files. This does that, and keeps the settings the same between them while allowing for defining different menus, e.g. `wlr-which-key power`, `wlr-which-key firefox` etc.

2024-07-29 16:58 UTC, LilleAila commented
> @LilleAila aha! Hadn't thought about that particular usecase, thanks! I've opted for a slightly different implementation. Let me know what you think.

LGTM! But maybe `commonSettings` should be renamed to just `settings`, to comply with the naming scheme of most other modules. I guess i could also be a co-maintainer.

2024-07-29 16:58 UTC, LilleAila approved these changes

2024-07-29 17:43 UTC, minijackson commented
> But maybe `commonSettings` should be renamed to just `settings`, to comply with the naming scheme of most other modules.

I'm not completely sure, this `settings` option doesn't map to a config file. If some user just does `programs.wlr-which-key.settings = { ... }`, it wouldn't do anything.

> I guess i could also be a co-maintainer.

Awesome! I'll add you

2024-07-29 17:48 UTC, minijackson commented
Hmmm, I've tried adding you @LilleAila but home-manager doesn't seem to know you:

```
       error: undefined variable 'LilleAila'

       at /home/minijackson/Documents/Dev/dev/github.com/nix-community/home-manager/modules/programs/wlr-which-key.nix:7:46:

            6| in {
            7|   meta.maintainers = with lib.maintainers; [ LilleAila mightyiam minijackson ];
             |                                              ^
            8|
```

2024-07-29 17:51 UTC, LilleAila commented
> Hmmm, I've tried adding you @LilleAila but home-manager doesn't seem to know you:
> 
> ```
>        error: undefined variable 'LilleAila'
> 
>        at /home/minijackson/Documents/Dev/dev/github.com/nix-community/home-manager/modules/programs/wlr-which-key.nix:7:46:
> 
>             6| in {
>             7|   meta.maintainers = with lib.maintainers; [ LilleAila mightyiam minijackson ];
>              |                                              ^
>             8|
> ```

Right, i forgot the PR adding me isn’t merget yet. I think the one in nixpkgs maintainers is though, otherwise it’s okay not to be added.

2024-07-29 17:55 UTC, minijackson commented
I think home-manager can use the maintainer list from nixpkgs. If you've added yourself in nixpkgs recently, might be that home-manager's nixpkgs is not recent enough.

2024-08-01 16:42 UTC, minijackson commented
@LilleAila after investigating a bit more, I think this is a "me" issue, since the way I tested it was using `import <nixpkgs>`. I've added you, and I guess we'll see if this goes well!

2024-08-24 19:45 UTC, IldenH requested changes
I think allowing users to ignore the `configs` or `menus` option as I've renamed it to and only use the normal `settings` is good.

2024-08-24 19:45 UTC, IldenH commented on modules/programs/wlr-which-key.nix
> +    enable = lib.mkEnableOption "wlr-which-key configuration";
```suggestion
    enable = lib.mkEnableOption "wlr-which-key";
```

2024-08-24 19:45 UTC, IldenH commented on modules/programs/wlr-which-key.nix
> +        The default configuration is named 'config'.
This line is confusing and I think it is unnecessary as those who only use one config will just run wlr-which-key without anything else.

2024-08-24 19:45 UTC, IldenH commented on modules/programs/wlr-which-key.nix
> +    configs = lib.mkOption {
```suggestion
    menus = lib.mkOption {
```

2024-08-24 19:45 UTC, IldenH commented on modules/programs/wlr-which-key.nix
> +        This enables you to run: `wlr-which-key ''${name}`
```suggestion
        This enables you to run: `wlr-which-key ''${name}`.
```

2024-08-24 19:45 UTC, IldenH commented on modules/programs/wlr-which-key.nix
> +    commonSettings = lib.mkOption {
```suggestion
    settings = lib.mkOption {
```

2024-08-24 19:45 UTC, IldenH commented on modules/programs/wlr-which-key.nix
> +      }) cfg.configs;
I think a config.yaml should be generated as well. Such that `settings.menu` works.

2024-08-24 19:45 UTC, IldenH commented on modules/programs/wlr-which-key.nix
> +        Settings to be applied to every configuration under the `configs` option.
```suggestion
        Settings to be applied to every menu specified under the `menus` option.
```

2024-10-04 13:04 UTC, minijackson commented
@IldenH I'm not sold on making `settings` both the configuration for the default file, and also apply them to the other `menus`. I think it's best to keep one option for common settings, and one option that map to files.

I've reworded the sentence explaining the default file, please tell me if it's still confusing.

I also prefer keeping `configs` since I feel that with `menus` it can be confused with the `menu` setting inside the config.

I agree that `programs.wlr-which-key.configs.config` feels clunky to write, but the name `config.yaml` is upstream's choice and I don't think we should hide it.

2024-12-27 23:09 UTC, Catmaniscatlord commented
This PR seems stale, but I have some feedback that might move things forward.

Packing the menus in a single variable and keeping the settings separate, unless you choose to override the settings for a specific menu is a complicated and confusing layout to configure this package. It seems that this was chosen so that settings can be shared between different menus. The user can do this in their own config by creating a local variable for the config ` let myStyle = { ... }; in ` and then using unions to override changed values with ` style = myStyle // { ... }`.

Putting the config that gets called by default into the `config` variable is intuitive. Also, any extra configs being in `extraConfigs` would make sense that you need to pass an argument to call those configs explicitly, without the help of a description.

``` nix
{
  programs.wlr-which-key = 
  let
   myStyle = {
    anchor = "center";
    background = "#282828d0";
    border = "#8ec07c";
    border_width = 2;
    color = "#fbf1c7";
    corner_r = 10;
    font = "JetBrainsMono Nerd Font 12";
    margin_bottom = 0;
    margin_left = 0;
    margin_right = 0;
    margin_top = 0;
    padding = 15;
    separator = " ➜ ";
   };
  in {
  enable = true;
  
  # Default Style
  config = {
    style = myStyle
    #Default config
    menu = {
      ...
    };
  };

  # Extra Configs if the user desires
  extraConfigs = {
    firefox = {
      style = myStyle // { border = "#ff0000"; };
      menu = {
         ...
      };
    };
  };
};
```

2025-03-28 08:47 UTC, hervyqa commented
no stale

2025-04-21 17:29 UTC, khaneliman commented
> This PR seems stale, but I have some feedback that might move things forward.
> 
> Packing the menus in a single variable and keeping the settings separate, unless you choose to override the settings for a specific menu is a complicated and confusing layout to configure this package. It seems that this was chosen so that settings can be shared between different menus. The user can do this in their own config by creating a local variable for the config `let myStyle = { ... }; in` and then using unions to override changed values with ` style = myStyle // { ... }`.
> 
> Putting the config that gets called by default into the `config` variable is intuitive. Also, any extra configs being in `extraConfigs` would make sense that you need to pass an argument to call those configs explicitly, without the help of a description.
> 
> ```nix
> {
>   programs.wlr-which-key = 
>   let
>    myStyle = {
>     anchor = "center";
>     background = "#282828d0";
>     border = "#8ec07c";
>     border_width = 2;
>     color = "#fbf1c7";
>     corner_r = 10;
>     font = "JetBrainsMono Nerd Font 12";
>     margin_bottom = 0;
>     margin_left = 0;
>     margin_right = 0;
>     margin_top = 0;
>     padding = 15;
>     separator = " ➜ ";
>    };
>   in {
>   enable = true;
>   
>   # Default config
>   config = {
>     style = myStyle
>     menu = {
>       ...
>     };
>   };
> 
>   # Extra Configs if the user desires
>   extraConfigs = {
>     firefox = {
>       style = myStyle // { border = "#ff0000"; };
>       menu = {
>          ...
>       };
>     };
>   };
> };
> ```

Yeah, I was reviewing module a bit and this did stand out as a weird UX. We should strive for as much of a nix -> config format transparency as possible. If the desire is just to deduplicate code in a user's config, they can leverage variables for that.

2025-09-03 08:51 UTC, minijackson commented
Sorry all, I've lost interest in becoming maintainer of this module. If anyone wants to pick this PR backup, please feel free!

2025-09-13 10:01 UTC, mightyiam commented
Sorry, a bit unrelated; is there an alternative to this that is already in home-manager?

2026-04-18 08:23 UTC, rachitvrma commented
```nix
    {
      config,
      lib,
      pkgs,
      ...
    }:
    let
      inherit (lib) mkIf mkOption types;
      cfg = config.programs.wlr-which-key;
      yamlFormat = pkgs.formats.yaml { };
    in
    {
      options.programs.wlr-which-key = {
        enable = lib.mkEnableOption "wlr-which-key";

        package = lib.mkPackageOption pkgs "wlr-which-key" { };

        settings = mkOption {
          inherit (yamlFormat) type;
          default = { };
          description = "Main wlr-which-key configuration written to config.yml.";
        };

        inheritSettings = mkOption {
          type = types.bool;
          default = false;
          description = "Whether extra menus inherit top-level settings from settings.";
        };

        extraMenus = mkOption {
          type = types.attrsOf yamlFormat.type;
          default = { };
          description = "Additional named menus, each written to wlr-which-key/<name>.yml.";
        };
      };

      config = mkIf cfg.enable {
        home.packages = [ cfg.package ];

        xdg.configFile = lib.mkMerge [
          (mkIf (cfg.settings != { }) {
            "wlr-which-key/config.yml".source = yamlFormat.generate "wlr-which-key-main" cfg.settings;
          })
          (lib.mapAttrs' (
            name: value:
            lib.nameValuePair "wlr-which-key/${name}.yml" {
              source = yamlFormat.generate "wlr-which-key-${name}" (
                lib.optionalAttrs cfg.inheritSettings cfg.settings // value
              );
            }
          ) cfg.extraMenus)
        ];
      };
    }
```

How about this? We can have an extra boolean option to whether inherit the main settings or not.

2026-08-06 15:47 UTC, closed without merging