home-manager: fix early exit due to FQDN error
nix-community/home-manager pull request #5738
Opened 2024-08-16 06:01 UTC by bryango

### Description

Closes #5711.

Since 89670e27e101b9b30f5900fc1eb6530258d316b1, FQDN lookup errors from `hostname -f` may cause an early exit of the whole program. This PR offers to solutions to the problem:

- The first commit fixes the issue at hand by absorbing the FQDN query inside the `if` statement.
- The second commit simply reverts back to the older simple logic, but now we pull in the GNU `inetutils` dependency whose `hostname` does not panic on failing FQDN queries. See: #5692.

### Checklist

- [ ] Change is backwards compatible.

- [ ] Code formatted with `./format`.

- [ ] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [ ] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

#### Maintainer CC

2024-08-16 06:34 UTC, bryango commented
Both commits are tested: works on my machine, at least!

2024-08-16 14:53 UTC, gauravjuvekar commented
LGTM, second approach of switching to inetutils feels more reliable to me if the command doesn't fail in the first place.

2024-08-16 14:54 UTC, gauravjuvekar commented
Also closes #5692

2024-08-17 02:16 UTC, bryango commented
cc @rycee for comments and review :wink:

2024-08-17 05:45 UTC, kenranunderscore commented
Hey @bryango, sorry for the ping, but I'm not sure I did my review right above. Please have a look at it, as the PR in its current state should not be able to run (and it doesn't if I try it out), since `inetutils` isn't bound after your commit in https://github.com/nix-community/home-manager/blob/9eabb4e8d755777a9f65106294a4f9068af28d0b/home-manager/default.nix#L1C1-L7C17. (And `unixtools` can be dropped.)

2024-08-17 05:48 UTC, kenranunderscore requested changes

2024-08-17 06:07 UTC, bryango commented on home-manager/default.nix
> +        inetutils # for `hostname`
Oh thank you sooo much! I tested this with a nixpkgs overlay which was properly set up, but apparently this original file is wrong...

2024-08-19 11:15 UTC, kenranunderscore commented
I can confirm that this works on my machine where I previously ran into #5711 :+1:

2024-08-23 03:06 UTC, bryango commented
@rycee We probably need to merge this, it's been tested by many people now. Either commit will fix the issue; feel free to pick one!

2024-08-26 06:46 UTC, kenranunderscore commented
Friendly ping as well: I'd love for this to be merged, as I currently run `nix run github:bryango/home-manager/fix-hostname -- switch --flake ~/dotfiles --impure --refresh` often, which is a *bit* unwieldy :smile:

2024-09-08 05:48 UTC, bryango commented
Friendly ping @rycee again... Sorry for the noise :laughing:

2024-09-13 06:56 UTC, merged

2024-09-13 06:56 UTC, rycee commented
Thanks! Apologies for the delay, merged to master now.

2024-09-14 10:29 UTC, m0ar commented
@bryango Thanks for fixing this! :heart: :cupcake: