trayscale: add module
nix-community/home-manager pull request #5803
Opened 2024-09-04 08:59 UTC by callumio

### Description

Trayscale is an unofficial GUI wrapper around the Tailscale CLI client.

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.

- [x] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [x] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

2024-09-04 16:41 UTC, sumnerevans requested changes

2024-09-04 16:41 UTC, sumnerevans commented on modules/services/trayscale.nix
> +      "An unofficial GUI wrapper around the Tailscale CLI client.";
```suggestion
      "trayscale, an unofficial GUI wrapper around the Tailscale CLI client";
```

2024-09-04 16:41 UTC, sumnerevans commented on modules/services/trayscale.nix
> +    };
```suggestion
    hideWindow = mkEnableOption "hide the trayscale window on startup" // {
      default = true;
    };
```

2024-09-04 16:41 UTC, sumnerevans commented on tests/modules/services/trayscale/hide-window.nix
> +    test.stubs = { trayscale = { }; };
```suggestion
    test.stubs.trayscale = { };
```

2024-09-04 16:41 UTC, sumnerevans commented on tests/modules/services/trayscale/show-window.nix
> +    test.stubs = { trayscale = { }; };
```suggestion
    test.stubs.trayscale = { };
```

2024-09-09 19:46 UTC, sumnerevans approved these changes
Please rebase and squash. Hopefully that will make at least the Ubuntu tests pass.

2024-09-13 09:00 UTC, rycee commented
Thanks! Rebased to master in 4c8647b1ed35d0e1822c7997172786dfa18cd7da 🙂

2024-09-13 09:00 UTC, closed without merging